In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
df = pd.read_csv('/content/OTT Subscriber.csv')

In [ ]:
df

,subscriber_id,age,gender,subscription_tenure_months,region,payment_method,support_tickets_raised,satisfaction_score,promo_discount_pct,days_since_last_activity,...,content_genre_preference,peak_viewing_hour,primary_device,num_devices_registered,download_feature_used,live_to_vod_ratio,subscription_plan,payment_failures,plan_change_history,data_source
0,SUB-00001,56.0,Male,54.00,LATAM,PayPal,0.00,9.000,6.42,319.00,...,Drama,Late Night,Smart TV,5.0,No,0.71,Premium,0.00,No Change,OTT_PLATFORM
1,SUB-00002,69.0,Female,21.00,APAC,Debit Card,1.00,2.000,13.77,166.00,...,Thriller,Evening,Console,3.0,No,0.69,Premium,1.00,Upgraded,OTT_PLATFORM
2,SUB-00003,46.0,Female,49.00,APAC,PayPal,3.00,8.000,19.91,207.00,...,Comedy,Late Night,Smart TV,6.0,No,0.31,Premium,2.00,Downgraded,OTT_PLATFORM
3,SUB-00004,32.0,Male,47.00,AMER,Debit Card,3.00,1.000,13.39,108.00,...,Reality,Morning,Desktop,6.0,No,0.74,Standard,0.00,Downgraded,OTT_PLATFORM
4,SUB-00005,60.0,Male,6.00,APAC,Credit Card,2.00,5.925,13.18,65.00,...,Comedy,Afternoon,Mobile,4.0,No,0.55,Premium,0.00,No Change,OTT_PLATFORM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10295,SUB-10296,39.0,Female,6.74,EMEA,Credit Card,1.98,4.780,7.01,241.33,...,News,Morning,Mobile,4.9,No,0.26,Standard,0.95,Upgraded,OTT_PLATFORM
10296,SUB-10297,26.0,Female,35.00,AMER,Debit Card,2.00,10.000,18.84,81.00,...,Reality,Afternoon,Smart TV,4.0,No,0.61,Premium,0.00,Upgraded,OTT_PLATFORM
10297,SUB-10298,59.0,Female,22.51,AMER,Credit Card,4.16,9.940,9.60,208.78,...,Thriller,Evening,Mobile,3.1,No,0.36,Standard,0.00,Downgraded,OTT_PLATFORM
10298,SUB-10299,44.0,Female,21.00,APAC,Credit Card,5.00,4.000,13.05,10.00,...,News,Evening,Smart TV,3.0,Yes,0.35,Standard,0.00,No Change,OTT_PLATFORM
10299,SUB-10300,41.0,Male,38.00,AMER,Credit Card,1.00,4.000,15.16,190.00,...,Thriller,Evening,Mobile,1.0,No,0.44,Standard,0.00,No Change,OTT_PLATFORM

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10300 entries, 0 to 10299
Data columns (total 59 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   subscriber_id                 10300 non-null  object
 1   age                           9940 non-null   float64
 2   gender                        10300 non-null  object
 3   subscription_tenure_months    10300 non-null  float64
 4   region                        10300 non-null  object
 5   payment_method                10300 non-null  object
 6   support_tickets_raised        10300 non-null  float64
 7   satisfaction_score            9920 non-null   float64
 8   promo_discount_pct            10300 non-null  float64
 9   days_since_last_activity      9900 non-null   float64
 10  monthly_spend_eur             10300 non-null  object
 11  churn                         10300 non-null  int64
 12  live_sports_subscriber        10300 non-null  object
 13  sports_events_watched_month   10300 non-null  float64
 14  favourite_live_sport          10300 non-null  object
 15  live_event_spike_signup       10300 non-null  object
 16  stream_quality_preference     10300 non-null  object
 17  bets_placed_total             10300 non-null  float64
 18  avg_bet_amount_eur            10300 non-null  float64
 19  avg_betting_odds              10300 non-null  float64
 20  betting_win_rate              10300 non-null  float64
 21  total_stake_eur               10300 non-null  float64
 22  total_gain_eur                10300 non-null  float64
 23  total_ggr                     10300 non-null  float64
 24  favourite_sport               10300 non-null  object
 25  preferred_bet_type            10300 non-null  object
 26  betting_enabled               10300 non-null  object
 27  responsible_gambling_flag     10300 non-null  object
 28  betting_profile               10300 non-null  object
 29  game_genre_preference         10300 non-null  object
 30  gaming_playtime_hours_weekly  10300 non-null  float64
 31  in_app_purchases_gaming       10300 non-null  float64
 32  gaming_sessions_per_week      10300 non-null  float64
 33  avg_gaming_session_mins       10300 non-null  float64
 34  gaming_engagement_level       10300 non-null  object
 35  ott_gaming_app_used           10300 non-null  object
 36  acquisition_channel           10300 non-null  object
 37  acquisition_campaign_type     10300 non-null  object
 38  ad_spend_eur                  10300 non-null  float64
 39  ctr                           10300 non-null  float64
 40  conversion_rate               10300 non-null  float64
 41  time_on_site_mins             10300 non-null  float64
 42  loyalty_points                10300 non-null  float64
 43  roas                          10300 non-null  float64
 44  used_free_trial               10300 non-null  object
 45  promo_discount_applied        10300 non-null  object
 46  avg_session_duration_mins     9960 non-null   float64
 47  titles_watched_per_month      10300 non-null  float64
 48  series_completion_rate        10300 non-null  float64
 49  content_genre_preference      10300 non-null  object
 50  peak_viewing_hour             10300 non-null  object
 51  primary_device                10300 non-null  object
 52  num_devices_registered        10300 non-null  float64
 53  download_feature_used         10300 non-null  object
 54  live_to_vod_ratio             10300 non-null  float64
 55  subscription_plan             10300 non-null  object
 56  payment_failures              10300 non-null  float64
 57  plan_change_history           10300 non-null  object
 58  data_source                   10300 non-null  object
dtypes: float64(30), int64(1), object(28)
memory usage: 4.6+ MB

In [ ]:
df.dtypes

subscriber_id                    object
age                             float64
gender                           object
subscription_tenure_months      float64
region                           object
payment_method                   object
support_tickets_raised          float64
satisfaction_score              float64
promo_discount_pct              float64
days_since_last_activity        float64
monthly_spend_eur                object
churn                             int64
live_sports_subscriber           object
sports_events_watched_month     float64
favourite_live_sport             object
live_event_spike_signup          object
stream_quality_preference        object
bets_placed_total               float64
avg_bet_amount_eur              float64
avg_betting_odds                float64
betting_win_rate                float64
total_stake_eur                 float64
total_gain_eur                  float64
total_ggr                       float64
favourite_sport                  object
preferred_bet_type               object
betting_enabled                  object
responsible_gambling_flag        object
betting_profile                  object
game_genre_preference            object
gaming_playtime_hours_weekly    float64
in_app_purchases_gaming         float64
gaming_sessions_per_week        float64
avg_gaming_session_mins         float64
gaming_engagement_level          object
ott_gaming_app_used              object
acquisition_channel              object
acquisition_campaign_type        object
ad_spend_eur                    float64
ctr                             float64
conversion_rate                 float64
time_on_site_mins               float64
loyalty_points                  float64
roas                            float64
used_free_trial                  object
promo_discount_applied           object
avg_session_duration_mins       float64
titles_watched_per_month        float64
series_completion_rate          float64
content_genre_preference         object
peak_viewing_hour                object
primary_device                   object
num_devices_registered          float64
download_feature_used            object
live_to_vod_ratio               float64
subscription_plan                object
payment_failures                float64
plan_change_history              object
data_source                      object
dtype: object

In [ ]:
df.describe()

,age,subscription_tenure_months,support_tickets_raised,satisfaction_score,promo_discount_pct,days_since_last_activity,churn,sports_events_watched_month,bets_placed_total,avg_bet_amount_eur,...,conversion_rate,time_on_site_mins,loyalty_points,roas,avg_session_duration_mins,titles_watched_per_month,series_completion_rate,num_devices_registered,live_to_vod_ratio,payment_failures
count,9940.000000,10300.000000,10300.000000,9920.00000,10300.000000,9900.000000,10300.000000,10300.000000,10300.000000,10300.000000,...,10300.000000,10300.000000,10300.000000,10300.000000,9960.000000,10300.000000,10300.000000,10300.000000,10300.000000,10300.000000
mean,43.963179,29.589677,2.032704,5.60231,12.496683,180.439778,0.147184,4.603684,19.992611,129.025011,...,0.103557,7.720586,2507.151694,220.173197,134.212553,39.914719,0.497801,3.545009,0.500736,0.310223
std,15.578164,17.090047,1.431039,3.05393,4.336032,104.234108,0.354307,6.217980,4.451797,148.572830,...,0.055113,4.211425,1426.790216,129.384034,176.483914,23.257610,0.288111,1.721269,0.290094,0.692347
min,-5.000000,0.000000,0.000000,-1.00000,4.620000,0.000000,0.000000,0.000000,6.000000,-706.880000,...,0.000000,0.290000,0.000000,0.000000,0.250000,0.000000,0.000000,0.760000,0.000000,0.000000
25%,32.000000,15.000000,1.000000,3.06000,8.760000,90.000000,0.000000,0.000000,17.000000,34.107500,...,0.055835,4.075614,1287.007500,105.947500,63.045000,20.000000,0.250000,2.000000,0.250000,0.000000
50%,44.000000,29.000000,2.000000,5.92500,12.540000,180.950000,0.000000,0.190000,20.000000,81.630000,...,0.101876,7.722966,2511.460000,220.690000,123.150000,40.000000,0.490000,3.950000,0.500000,0.000000
75%,55.000000,44.105000,3.000000,8.00000,16.210000,269.000000,0.000000,9.000000,23.000000,174.920000,...,0.150000,11.370097,3710.650000,333.297500,181.202500,60.000000,0.750000,5.000000,0.760000,0.030000
max,200.000000,61.210000,9.000000,99.00000,20.360000,377.560000,1.000000,19.820000,39.300000,815.880000,...,0.200000,15.390000,5109.350000,457.680000,2747.000000,81.410000,1.030000,6.320000,1.020000,3.080000

In [ ]:
# Number of missing values ​​in each column
missing_data = df.isnull().sum()
print(missing_data[missing_data > 0]) # Display only the columns that are missing

age                          360
satisfaction_score           380
days_since_last_activity     400
avg_session_duration_mins    340
dtype: int64

In [ ]:
# Percentage of missing values ​​in each column
missing_data = df.isnull().sum() / len(df) * 100
print(missing_data[missing_data > 0]) # Display only the columns that are missing

age                          3.495146
satisfaction_score           3.689320
days_since_last_activity     3.883495
avg_session_duration_mins    3.300971
dtype: float64

In [ ]:
# Selecting all columns except the subscriber_id column
cols_to_check = [col for col in df.columns if col != 'subscriber_id']
print(cols_to_check)

['age', 'gender', 'subscription_tenure_months', 'region', 'payment_method', 'support_tickets_raised', 'satisfaction_score', 'promo_discount_pct', 'days_since_last_activity', 'monthly_spend_eur', 'churn', 'live_sports_subscriber', 'sports_events_watched_month', 'favourite_live_sport', 'live_event_spike_signup', 'stream_quality_preference', 'bets_placed_total', 'avg_bet_amount_eur', 'avg_betting_odds', 'betting_win_rate', 'total_stake_eur', 'total_gain_eur', 'total_ggr', 'favourite_sport', 'preferred_bet_type', 'betting_enabled', 'responsible_gambling_flag', 'betting_profile', 'game_genre_preference', 'gaming_playtime_hours_weekly', 'in_app_purchases_gaming', 'gaming_sessions_per_week', 'avg_gaming_session_mins', 'gaming_engagement_level', 'ott_gaming_app_used', 'acquisition_channel', 'acquisition_campaign_type', 'ad_spend_eur', 'ctr', 'conversion_rate', 'time_on_site_mins', 'loyalty_points', 'roas', 'used_free_trial', 'promo_discount_applied', 'avg_session_duration_mins', 'titles_watched_per_month', 'series_completion_rate', 'content_genre_preference', 'peak_viewing_hour', 'primary_device', 'num_devices_registered', 'download_feature_used', 'live_to_vod_ratio', 'subscription_plan', 'payment_failures', 'plan_change_history', 'data_source']

In [ ]:
# Checking number of duplicate values on subset
df.duplicated(subset= cols_to_check).sum()

np.int64(1721)

In [ ]:
# Removing duplicates based on subset and keep only the first occurrence
df = df.drop_duplicates(subset= cols_to_check, keep='first')

In [ ]:
# Checking number of duplicate values after removing duplicates based on subset
df.duplicated(subset= cols_to_check).sum()

np.int64(0)

In [ ]:
# Converting monthly_spend_eur to numeric
df['monthly_spend_eur'] = pd.to_numeric(df['monthly_spend_eur'], errors='coerce')

/tmp/ipykernel_427/3054050862.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['monthly_spend_eur'] = pd.to_numeric(df['monthly_spend_eur'], errors='coerce')

In [ ]:
# Selecting float and int columns only
num_cols = df.select_dtypes(include=['float64', 'int64']).columns

# Checking for negative values in the specified columns
for col in num_cols:
    if col in df.columns:
        neg_count = len(df[df[col] < 0])
        if neg_count > 0:
            print(f"⚠️ col '{col}': there are {neg_count} negative values")
        else:
            print(f"✅ col '{col}': clean (no negative values)")

⚠️ col 'age': there are 5 negative values
✅ col 'subscription_tenure_months': clean (no negative values)
✅ col 'support_tickets_raised': clean (no negative values)
⚠️ col 'satisfaction_score': there are 4 negative values
✅ col 'promo_discount_pct': clean (no negative values)
✅ col 'days_since_last_activity': clean (no negative values)
⚠️ col 'monthly_spend_eur': there are 76 negative values
✅ col 'churn': clean (no negative values)
✅ col 'sports_events_watched_month': clean (no negative values)
✅ col 'bets_placed_total': clean (no negative values)
⚠️ col 'avg_bet_amount_eur': there are 94 negative values
✅ col 'avg_betting_odds': clean (no negative values)
✅ col 'betting_win_rate': clean (no negative values)
✅ col 'total_stake_eur': clean (no negative values)
✅ col 'total_gain_eur': clean (no negative values)
⚠️ col 'total_ggr': there are 1980 negative values
✅ col 'gaming_playtime_hours_weekly': clean (no negative values)
✅ col 'in_app_purchases_gaming': clean (no negative values)
✅ col 'gaming_sessions_per_week': clean (no negative values)
✅ col 'avg_gaming_session_mins': clean (no negative values)
⚠️ col 'ad_spend_eur': there are 62 negative values
✅ col 'ctr': clean (no negative values)
✅ col 'conversion_rate': clean (no negative values)
✅ col 'time_on_site_mins': clean (no negative values)
✅ col 'loyalty_points': clean (no negative values)
✅ col 'roas': clean (no negative values)
✅ col 'avg_session_duration_mins': clean (no negative values)
✅ col 'titles_watched_per_month': clean (no negative values)
✅ col 'series_completion_rate': clean (no negative values)
✅ col 'num_devices_registered': clean (no negative values)
✅ col 'live_to_vod_ratio': clean (no negative values)
✅ col 'payment_failures': clean (no negative values)

In [ ]:
# Selecting text columns only
text_cols = df.select_dtypes(include=['object']).columns

# Checking hidden spaces (extra spaces)
for col in text_cols:
    has_spaces = df[col].astype(str).str.contains(r'^\s|\s$', regex=True).sum() # counts how many values in column [col] have spaces at the beginning or end

    if has_spaces > 0:
        print(f"⚠️ col [{col}]: there are {has_spaces} rows with extra spaces")
    else:
        print(f"✅ col [{col}]: clean (no extra spaces)")

✅ col [subscriber_id]: clean (no extra spaces)
✅ col [gender]: clean (no extra spaces)
✅ col [region]: clean (no extra spaces)
✅ col [payment_method]: clean (no extra spaces)
✅ col [live_sports_subscriber]: clean (no extra spaces)
✅ col [favourite_live_sport]: clean (no extra spaces)
✅ col [live_event_spike_signup]: clean (no extra spaces)
✅ col [stream_quality_preference]: clean (no extra spaces)
✅ col [favourite_sport]: clean (no extra spaces)
✅ col [preferred_bet_type]: clean (no extra spaces)
✅ col [betting_enabled]: clean (no extra spaces)
✅ col [responsible_gambling_flag]: clean (no extra spaces)
✅ col [betting_profile]: clean (no extra spaces)
✅ col [game_genre_preference]: clean (no extra spaces)
✅ col [gaming_engagement_level]: clean (no extra spaces)
✅ col [ott_gaming_app_used]: clean (no extra spaces)
⚠️ col [acquisition_channel]: there are 81 rows with extra spaces
✅ col [acquisition_campaign_type]: clean (no extra spaces)
✅ col [used_free_trial]: clean (no extra spaces)
✅ col [promo_discount_applied]: clean (no extra spaces)
✅ col [content_genre_preference]: clean (no extra spaces)
✅ col [peak_viewing_hour]: clean (no extra spaces)
✅ col [primary_device]: clean (no extra spaces)
✅ col [download_feature_used]: clean (no extra spaces)
✅ col [subscription_plan]: clean (no extra spaces)
✅ col [plan_change_history]: clean (no extra spaces)
✅ col [data_source]: clean (no extra spaces)

In [ ]:
# Replaceing unrealistic age values (less than 15 or greater than 85) with NaN (missing value)
df.loc[(df['age'] < 15) | (df['age'] > 85), 'age'] = np.nan

# Filling missing values with Median
df.loc[:, 'age'] = df['age'].fillna(df['age'].median())

# Changing the data type of the age column to integer
df['age'] = df['age'].astype(int)

# Grouping age into age_groups
def age_bins(age):
    if age < 25:
      return '1. Gen Z (<25)'
    elif age < 40:
      return '2. Millennials (25-39)'
    elif age < 60:
      return '3. Gen X (40-59)'
    else:
       return '4. Boomers (60+)'

# Creating a new column 'age_group' in the DataFrame 'df'
df['age_group'] = df['age'].apply(age_bins)

# Checking the result (sample display)
print(df[['age', 'age_group']].sample(10))

# Checking the value counts of the 'age_group' column to see the distribution of age groups in the dataset
df['age_group'].value_counts().sort_index()

      age               age_group
3444   48        3. Gen X (40-59)
2927   45        3. Gen X (40-59)
4030   67        4. Boomers (60+)
5641   35  2. Millennials (25-39)
2260   32  2. Millennials (25-39)
965    47        3. Gen X (40-59)
2340   36  2. Millennials (25-39)
4233   32  2. Millennials (25-39)
7465   44        3. Gen X (40-59)
7921   49        3. Gen X (40-59)

/tmp/ipykernel_427/3165583468.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age'] = df['age'].astype(int)
/tmp/ipykernel_427/3165583468.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age_group'] = df['age'].apply(age_bins)

age_group
1. Gen Z (<25)             945
2. Millennials (25-39)    2172
3. Gen X (40-59)          3984
4. Boomers (60+)          1478
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'gender' column to see the distribution of gender in the dataset
df['gender'].value_counts()

gender
Female    4344
Male      4235
Name: count, dtype: int64

In [ ]:
# Replacing any negative values in the subscription_tenure_months column with 0.0
df.loc[df['subscription_tenure_months'] < 0.0, 'subscription_tenure_months'] = 0.0

# Type casting (implicit type conversion)
df['subscription_tenure_months'] = df['subscription_tenure_months'] + 0.0 # Removing the (Negative Zero)

# Rounding subscription_tenure_months to 2 decimal places
df['subscription_tenure_months'] = df['subscription_tenure_months'].round(2)

# Gruoping subscription_tenure_months into tenure groups
def categorize_tenure(months): # Definition of the classification function
    if months < 1.0:
      return '1. New User (<1 Month)'
    elif months <= 6.0:
      return '2. Short Term (1-6 Months)'
    elif months <= 12.0:
      return '3. Mid Term (6-12 Months)'
    elif months <= 24.0:
      return '4. Long Term (1-2 Years)'
    else:
      return '5. Loyal (2+ Years)'

# Creating a new column 'tenure_group' in the DataFrame 'df'
df['tenure_group'] = df['subscription_tenure_months'].apply(categorize_tenure)

# Checking the result (sample display)
print(df[['subscription_tenure_months', 'tenure_group']].sample(10))

# Checking the value counts of the 'tenure_group' column to see the distribution of tenure groups in the dataset
df['tenure_group'].value_counts().sort_index()

      subscription_tenure_months                tenure_group
4137                       57.00         5. Loyal (2+ Years)
5729                       42.41         5. Loyal (2+ Years)
6980                       47.55         5. Loyal (2+ Years)
2720                       26.00         5. Loyal (2+ Years)
6237                       15.98    4. Long Term (1-2 Years)
1562                        8.00   3. Mid Term (6-12 Months)
7383                       49.21         5. Loyal (2+ Years)
3387                        5.00  2. Short Term (1-6 Months)
1618                        3.00  2. Short Term (1-6 Months)
2197                       16.00    4. Long Term (1-2 Years)

/tmp/ipykernel_427/108081012.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['subscription_tenure_months'] = df['subscription_tenure_months'] + 0.0 # Removing the (Negative Zero)
/tmp/ipykernel_427/108081012.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['subscription_tenure_months'] = df['subscription_tenure_months'].round(2)
/tmp/ipykernel_427/108081012.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tenure_group'] = df['subscription_tenure_months'].apply(categorize_tenure)

tenure_group
1. New User (<1 Month)          26
2. Short Term (1-6 Months)     829
3. Mid Term (6-12 Months)      909
4. Long Term (1-2 Years)      1799
5. Loyal (2+ Years)           5016
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'region' column to see the distribution of regions in the dataset
df['region'].value_counts()

region
AMER     2283
EMEA     2134
LATAM    2105
APAC     2057
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'payment_method' column to see the distribution of payment methods in the dataset
df['payment_method'].value_counts()

payment_method
Debit Card     2899
PayPal         2869
Credit Card    2811
Name: count, dtype: int64

In [ ]:
# Rounding support_tickets_raised to the nearest integer
df['support_tickets_raised'] = df['support_tickets_raised'].round(0).astype(int)

# Grouping support_tickets_raised into support_groups
def classify_support(tickets): # Definition of the classification function
    if tickets == 0:
      return '0. No Issues'
    elif tickets <= 2:
      return '1. Low Support Needs'
    else:
      return '2. High Support Needs (Potential Churn)'

# Creating a new column 'support_priority' in the DataFrame 'df'
df['support_priority'] = df['support_tickets_raised'].apply(classify_support)

# Checking the result (sample display)
print(df[['support_tickets_raised', 'support_priority']].sample(10))

# Checking the value counts of the 'support_priority' column to see the distribution of support priorities in the dataset
df['support_priority'].value_counts().sort_index()

       support_tickets_raised                         support_priority
217                         2                     1. Low Support Needs
10087                       1                     1. Low Support Needs
5609                        1                     1. Low Support Needs
6246                        1                     1. Low Support Needs
9589                        1                     1. Low Support Needs
180                         1                     1. Low Support Needs
2451                        2                     1. Low Support Needs
9970                        3  2. High Support Needs (Potential Churn)
6248                        2                     1. Low Support Needs
9417                        1                     1. Low Support Needs

/tmp/ipykernel_427/1488518786.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['support_tickets_raised'] = df['support_tickets_raised'].round(0).astype(int)
/tmp/ipykernel_427/1488518786.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['support_priority'] = df['support_tickets_raised'].apply(classify_support)

support_priority
0. No Issues                               1100
1. Low Support Needs                       4685
2. High Support Needs (Potential Churn)    2794
Name: count, dtype: int64

In [5]:
# Making sure there are no negative values ​​(the minimum is 0) and Handling extreme values ​​(Outliers)
df['satisfaction_score'] = df['satisfaction_score'].clip(lower=0, upper=10)

# Filling missing values with Median
df['satisfaction_score'] = df['satisfaction_score'].fillna(df['satisfaction_score'].median())

# Rounding satisfaction_score to the nearest integer
df['satisfaction_score'] = df['satisfaction_score'].round(0).astype(int)

# Grouping satisfaction_score into satisfaction groups
def categorize_satisfaction(score):
    if score <= 3:
      return '1. Detractors (Unsatisfied)'
    elif score <= 7:
      return '2. Passives (Neutral)'
    else:
      return '3. Promoters'

# Creating a new column 'satisfaction_group' in the DataFrame 'df'
df['satisfaction_group'] = df['satisfaction_score'].apply(categorize_satisfaction)

# Checking the result (sample display)
print(df[['satisfaction_score', 'satisfaction_group']].sample(10))

# Checking the value counts of the 'satisfaction_score' column to see the distribution of satisfaction scores in the dataset
df['satisfaction_group'].value_counts().sort_index()

      satisfaction_score           satisfaction_group
7613                   7        2. Passives (Neutral)
4308                   5        2. Passives (Neutral)
2204                   4        2. Passives (Neutral)
2322                   7        2. Passives (Neutral)
5374                   8                 3. Promoters
9532                   6        2. Passives (Neutral)
1642                   9                 3. Promoters
6837                   2  1. Detractors (Unsatisfied)
722                    9                 3. Promoters
3938                   6        2. Passives (Neutral)

satisfaction_group
1. Detractors (Unsatisfied)    2582
2. Passives (Neutral)          5003
3. Promoters                   2715
Name: count, dtype: int64

In [ ]:
# Making sure there are no negative values ​​(the minimum is 0) and Handling extreme values ​​(Outliers)
df['promo_discount_pct'] = df['promo_discount_pct'].clip(lower=0.0, upper=30.0) # Assuming that the maximum reasonable discount is 30

# Rounding promo_discount_pct to 2 decimal places
df['promo_discount_pct'] = df['promo_discount_pct'].round(2)

# Grouping promo_discount_pct into discount groups
def categorize_discount(pct):
  if pct <= 5.0:
    return '1. Starter (0-5%)'
  elif pct <= 15.0:
    return '2. Silver (5-15%)'
  else:
    return '3. Gold (>15%)'

# Creating a new column 'discount_group' in the DataFrame 'df'
df['discount_group'] = df['promo_discount_pct'].apply(categorize_discount)

# Checking the result (sample display)
print(df[['promo_discount_pct', 'discount_group']].sample(10))

# Checking the value counts of the 'discount_group' column to see the distribution of discount groups in the dataset
df['discount_group'].value_counts().sort_index()

      promo_discount_pct     discount_group
6935               19.40     3. Gold (>15%)
1450               14.46  2. Silver (5-15%)
496                18.16     3. Gold (>15%)
9468               17.79     3. Gold (>15%)
139                 6.65  2. Silver (5-15%)
725                17.52     3. Gold (>15%)
3837               11.02  2. Silver (5-15%)
4523                5.50  2. Silver (5-15%)
6736               19.09     3. Gold (>15%)
7778               11.03  2. Silver (5-15%)

/tmp/ipykernel_427/3006730946.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['promo_discount_pct'] = df['promo_discount_pct'].clip(lower=0.0, upper=30.0) # Assuming that the maximum reasonable discount is 30
/tmp/ipykernel_427/3006730946.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['promo_discount_pct'] = df['promo_discount_pct'].round(2)
/tmp/ipykernel_427/3006730946.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['discount_group'] = df['promo_discount_pct'].apply(categorize_discount)

discount_group
1. Starter (0-5%)      24
2. Silver (5-15%)    5715
3. Gold (>15%)       2840
Name: count, dtype: int64

In [ ]:
# Filling missing values in the 'days_since_last_activity' column with 999 to mark them forever since last activity
df['days_since_last_activity'] = df['days_since_last_activity'].fillna(999.0)

# Type casting (implicit type conversion)
df['days_since_last_activity'] = df['days_since_last_activity'] + 0.0 # Removing the (Negative Zero)

# Rounding days_since_last_activity to 2 decimal places
df['days_since_last_activity'] = df['days_since_last_activity'].round(2)

# Groupings days_since_last_activity into activity groups
def categorize_activity(days):
  if days == 999.0:
    return '0. Never Active'
  elif days <= 1.0:
    return '1. Very Active (Today)'
  elif days <= 7.0:
    return '2. Active (This Week)'
  elif days <= 30.0:
    return '3. Slipping (Past Month)'
  elif days <= 90.0:
    return '4. At Risk (1-3 Months)'
  else:
    return '5. Inactive (>3 Months)'

# Creating a new column 'activity_status' in the DataFrame 'df'
df['activity_status'] = df['days_since_last_activity'].apply(categorize_activity)

# Checking the result (sample display)
print(df[['days_since_last_activity', 'activity_status']].sample(10))

# Checing the value counts of the 'activity_status' column to see the distribution of activity statuses in the dataset
df['activity_status'].value_counts().sort_index()

      days_since_last_activity          activity_status
7085                      6.50    2. Active (This Week)
7530                    358.00  5. Inactive (>3 Months)
5753                     44.01  4. At Risk (1-3 Months)
4137                    108.00  5. Inactive (>3 Months)
5857                    304.26  5. Inactive (>3 Months)
4410                    257.00  5. Inactive (>3 Months)
895                     357.00  5. Inactive (>3 Months)
498                      37.00  4. At Risk (1-3 Months)
2900                    140.00  5. Inactive (>3 Months)
1990                    351.00  5. Inactive (>3 Months)

/tmp/ipykernel_427/1664929845.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['days_since_last_activity'] = df['days_since_last_activity'].fillna(999.0)
/tmp/ipykernel_427/1664929845.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['days_since_last_activity'] = df['days_since_last_activity'] + 0.0 # Removing the (Negative Zero)
/tmp/ipykernel_427/1664929845.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['days_since_last_activity'] = df['days_since_last_activity'].round(2)
/tmp/ipykernel_427/1664929845.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['activity_status'] = df['days_since_last_activity'].apply(categorize_activity)

activity_status
0. Never Active              247
1. Very Active (Today)        35
2. Active (This Week)        125
3. Slipping (Past Month)     534
4. At Risk (1-3 Months)     1406
5. Inactive (>3 Months)     6232
Name: count, dtype: int64

In [ ]:
# Converting monthly_spend_eur to text to handle the Euro symbol
df['monthly_spend_eur'] = df['monthly_spend_eur'].astype(str)

# Removing the Euro symbol and any spaces
df['monthly_spend_eur'] = df['monthly_spend_eur'].str.replace('â‚¬', '', regex=False).str.strip()

# Converting monthly_spend_eur to numeric
df['monthly_spend_eur'] = pd.to_numeric(df['monthly_spend_eur'], errors='coerce')

# Type casting (implicit type conversion)
df['monthly_spend_eur'] = df['monthly_spend_eur'] + 0.0 # Removing the (Negative Zero)

# Rounding monthly_spend_eur to 2 decimal places
df['monthly_spend_eur'] = df['monthly_spend_eur'].round(2)

# Converting negative values to zero
df.loc[df['monthly_spend_eur'] < 0.0, 'monthly_spend_eur'] = 0.0

# Filling missing values with Median
df['monthly_spend_eur'] = df['monthly_spend_eur'].fillna(df['monthly_spend_eur'].median())

# Grouping monthly_spend_eur into spend groups
def categorize_spend(amount):
  if amount == 0.0:
    return '0. Free/Refunded'
  elif amount <=30.0:
    return '1. Basic (<30 eur)'
  elif amount <= 70.0:
    return '2. Standard (30-70 eur)'
  else:
    return '3. Premium (>70 eur)'

# Creating a new column 'spend_tier' in the DataFrame 'df'
df['spend_tier'] = df['monthly_spend_eur'].apply(categorize_spend)

# Checking the result (sample display)
print(df[['monthly_spend_eur', 'spend_tier']].sample(10))

# Checking the value counts of the 'spend_tier' column to see the distribution of spend tiers in the dataset
df['spend_tier'].value_counts().sort_index()

      monthly_spend_eur               spend_tier
1553              51.43  2. Standard (30-70 eur)
6635              53.08  2. Standard (30-70 eur)
6543              26.42       1. Basic (<30 eur)
1551              50.79  2. Standard (30-70 eur)
7179              53.08  2. Standard (30-70 eur)
1664              33.54  2. Standard (30-70 eur)
7750              45.73  2. Standard (30-70 eur)
6555              38.51  2. Standard (30-70 eur)
235               51.99  2. Standard (30-70 eur)
538               29.34       1. Basic (<30 eur)

/tmp/ipykernel_427/1572709159.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['monthly_spend_eur'] = df['monthly_spend_eur'].astype(str)
/tmp/ipykernel_427/1572709159.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['monthly_spend_eur'] = df['monthly_spend_eur'].str.replace('â‚¬', '', regex=False).str.strip()
/tmp/ipykernel_427/1572709159.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['monthly_spend_eur'] = pd.to_numeric(df['monthly_spend_eur'], errors='coerce')
/tmp/ipykernel_427/1572709159.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['monthly_spend_eur'] = df['monthly_spend_eur'] + 0.0 # Removing the (Negative Zero)
/tmp/ipykernel_427/1572709159.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['monthly_spend_eur'] = df['monthly_spend_eur'].round(2)
/tmp/ipykernel_427/1572709159.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['monthly_spend_eur'] = df['monthly_spend_eur'].fillna(df['monthly_spend_eur'].median())
/tmp/ipykernel_427/1572709159.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spend_tier'] = df['monthly_spend_eur'].apply(categorize_spend)

spend_tier
0. Free/Refunded             78
1. Basic (<30 eur)          310
2. Standard (30-70 eur)    8187
3. Premium (>70 eur)          4
Name: count, dtype: int64

In [ ]:
# Creating a new column 'churn_status' in the DataFrame 'df'
df['churn_status'] = df['churn'].map({0: 'Retained (Active)', 1: 'Churned (Left)'})

# Checking the result (sample display)
print(df[['churn', 'churn_status']].sample(10))

# Checking the value counts of the 'churn_status' column to see the distribution of churn statuses in the dataset
df['churn_status'].value_counts()

      churn       churn_status
3316      1     Churned (Left)
6831      0  Retained (Active)
5742      1     Churned (Left)
4008      0  Retained (Active)
4922      0  Retained (Active)
4573      0  Retained (Active)
236       0  Retained (Active)
2873      0  Retained (Active)
6788      0  Retained (Active)
8123      0  Retained (Active)

/tmp/ipykernel_427/2079597920.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['churn_status'] = df['churn'].map({0: 'Retained (Active)', 1: 'Churned (Left)'})

churn_status
Retained (Active)    7307
Churned (Left)       1272
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'live_sports_subscriber' column to see the distribution of live sports subscribers in the dataset
df['live_sports_subscriber'].value_counts()

live_sports_subscriber
No     4664
Yes    3915
Name: count, dtype: int64

In [ ]:
# Rounding sports_events_watched_month to the nearest integer
df['sports_events_watched_month'] = df['sports_events_watched_month'].round(0).astype(int)

# Grouping sports_events_watched_month into sports_groups
def categorize_sports(events):
  if events == 0:
    return '0. None (0)'
  elif events <= 5:
    return '1. Low (1-5)'
  elif events <= 12:
    return '2. Medium (6-12)'
  else:
    return '3. High (>12)'

# Creating a new column 'sports_engagement' in the DataFrame 'df'
df['sports_engagement'] = df['sports_events_watched_month'].apply(categorize_sports)

# Checking the result (sample display)
print(df[['sports_events_watched_month', 'sports_engagement']].sample(10))

# Checking the value counts of the 'sports_engagement' column to see the distribution of sports engagement in the dataset
df['sports_engagement'].value_counts().sort_index()

      sports_events_watched_month sports_engagement
6090                            5      1. Low (1-5)
3614                            2      1. Low (1-5)
1046                            8  2. Medium (6-12)
6875                            3      1. Low (1-5)
851                             0       0. None (0)
9687                            5      1. Low (1-5)
3450                            0       0. None (0)
777                             0       0. None (0)
6050                            0       0. None (0)
3320                            0       0. None (0)

/tmp/ipykernel_427/1622050851.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sports_events_watched_month'] = df['sports_events_watched_month'].round(0).astype(int)
/tmp/ipykernel_427/1622050851.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sports_engagement'] = df['sports_events_watched_month'].apply(categorize_sports)

sports_engagement
0. None (0)         4586
1. Low (1-5)        1070
2. Medium (6-12)    1453
3. High (>12)       1470
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'favourite_live_sport' column to see the distribution of favourite life sports in the dataset
df['favourite_live_sport'].value_counts()

favourite_live_sport
Not Applicable    4664
Football          1355
F1                 802
Tennis             737
Boxing             388
Basketball         368
Cricket            265
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'live_event_spike_signup' column to see the distribution of live event spike signups in the dataset
df['live_event_spike_signup'].value_counts()

live_event_spike_signup
No     7367
Yes    1212
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'stream_quality_preference' column to see the distribution of stream quality preferences in the dataset
df['stream_quality_preference'].value_counts()

stream_quality_preference
HD     3916
4K     2955
HDR     909
SD      799
Name: count, dtype: int64

In [ ]:
# Rounding avg_bet_amount_eur to the nearest integer
df['bets_placed_total'] = df['bets_placed_total'].round(0).astype(int)

# Grouping bets_placed_total into bet_groups
def get_betting_style(bets):
  if bets <= 5:
    return '1. Occasional (0-5)'
  elif bets <= 15:
    return '2. Active (6-15)'
  elif bets <= 30:
    return '3. Frequent (16-30)'
  else:
    return '4. Heavy Bettor (>30)'

# Creating a new column 'betting_intensity' in the DataFrame 'df'
df['betting_intensity'] = df['bets_placed_total'].apply(get_betting_style)

# Checking the result (sample display)
print(df[['bets_placed_total', 'betting_intensity']].sample(10))

# Checking the value counts of the 'betting_intensity' column to see the distribution of betting intensities in the dataset
df['betting_intensity'].value_counts().sort_index()

      bets_placed_total    betting_intensity
6880                 18  3. Frequent (16-30)
593                  21  3. Frequent (16-30)
2435                 21  3. Frequent (16-30)
7014                 23  3. Frequent (16-30)
3378                 18  3. Frequent (16-30)
4989                 20  3. Frequent (16-30)
2045                 24  3. Frequent (16-30)
5995                 20  3. Frequent (16-30)
6902                 20  3. Frequent (16-30)
1754                 27  3. Frequent (16-30)

/tmp/ipykernel_427/146461911.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bets_placed_total'] = df['bets_placed_total'].round(0).astype(int)
/tmp/ipykernel_427/146461911.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['betting_intensity'] = df['bets_placed_total'].apply(get_betting_style)

betting_intensity
2. Active (6-15)         1337
3. Frequent (16-30)      7138
4. Heavy Bettor (>30)     104
Name: count, dtype: int64

In [ ]:
# Replacing any negative values in the avg_bet_amount_eur column with 0
df.loc[df['avg_bet_amount_eur'] < 0.0, 'avg_bet_amount_eur'] = 0.0

# Type casting (implicit type conversion)
df['avg_bet_amount_eur'] = df['avg_bet_amount_eur'] + 0.0 # Removeing the (Negative Zero)

# Rounding avg_bet_amount_eur to 2 decimal places
df['avg_bet_amount_eur'] = df['avg_bet_amount_eur'].round(2)

# Groupings avg_bet_amount_eur into bet_groups
def get_monetary_segment(amount):
  if amount == 0.0:
    return '0. Non-Spender'
  elif amount <= 5.0:
    return '1. Micro Bettor (<5 eur)'
  elif amount <= 50.0:
    return '2. Standard (5-50 eur)'
  elif amount <= 200.0:
    return '4. High Roller (50-200 eur)'
  else:
    return '5. Whale / VIP (>200 eur)'

# Creating a new column 'customer_value_segment' in the DataFrame 'df'
df['customer_value_segment'] = df['avg_bet_amount_eur'].apply(get_monetary_segment)

# Checking the result (sample display)
print(df[['avg_bet_amount_eur', 'customer_value_segment']].sample(10))

# Checking the value counts of the 'customer_value_segment' column to see the distribution of customer value segments in the dataset
df['customer_value_segment'].value_counts().sort_index()

/tmp/ipykernel_427/3000545091.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['avg_bet_amount_eur'] = df['avg_bet_amount_eur'] + 0.0 # Removeing the (Negative Zero)
/tmp/ipykernel_427/3000545091.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['avg_bet_amount_eur'] = df['avg_bet_amount_eur'].round(2)

      avg_bet_amount_eur       customer_value_segment
8479                5.69       2. Standard (5-50 eur)
1081              609.84    5. Whale / VIP (>200 eur)
1386               77.93  4. High Roller (50-200 eur)
6555              319.31    5. Whale / VIP (>200 eur)
4840               87.30  4. High Roller (50-200 eur)
6767              347.58    5. Whale / VIP (>200 eur)
6811              411.86    5. Whale / VIP (>200 eur)
3552               74.38  4. High Roller (50-200 eur)
1671              195.38  4. High Roller (50-200 eur)
6519               73.67  4. High Roller (50-200 eur)

/tmp/ipykernel_427/3000545091.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['customer_value_segment'] = df['avg_bet_amount_eur'].apply(get_monetary_segment)

customer_value_segment
0. Non-Spender                  152
1. Micro Bettor (<5 eur)        313
2. Standard (5-50 eur)         2881
4. High Roller (50-200 eur)    3667
5. Whale / VIP (>200 eur)      1566
Name: count, dtype: int64

In [ ]:
# Zeroing out any false values ​​less than 1 (mathematically impossible in ODS)
df['avg_betting_odds'] = df['avg_betting_odds'].clip(lower=1.0)

# Rounding avg_betting_odds to 2 decimal places
df['avg_betting_odds'] = df['avg_betting_odds'].round(2)

# Grouping avg_betting_odds into odds_groups
def get_risk_profile(odds):
  if odds <= 2.0:
    return '1. Conservative (Low Odds)'
  elif odds <= 5.0:
    return '2. Moderate (Medium Odds)'
  else:
    return '3. High Risk / Dreamer (High Odds)'

# Creating a new column 'risk_profile' in the DataFrame 'df'
df['risk_profile'] = df['avg_betting_odds'].apply(get_risk_profile)

# Checking the result (sample display)
print(df[['avg_betting_odds', 'risk_profile']].sample(10))

# Checking the value counts of the 'risk_profile' column to see the distribution of risk profiles in the dataset
df['risk_profile'].value_counts().sort_index()

      avg_betting_odds                        risk_profile
7291              3.54           2. Moderate (Medium Odds)
159               4.54           2. Moderate (Medium Odds)
5538              3.85           2. Moderate (Medium Odds)
44                4.87           2. Moderate (Medium Odds)
2312              6.76  3. High Risk / Dreamer (High Odds)
2957              3.85           2. Moderate (Medium Odds)
57                6.41  3. High Risk / Dreamer (High Odds)
5472              6.67  3. High Risk / Dreamer (High Odds)
1618              2.82           2. Moderate (Medium Odds)
3486              4.02           2. Moderate (Medium Odds)

/tmp/ipykernel_427/2304121476.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['avg_betting_odds'] = df['avg_betting_odds'].clip(lower=1.0)
/tmp/ipykernel_427/2304121476.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['avg_betting_odds'] = df['avg_betting_odds'].round(2)
/tmp/ipykernel_427/2304121476.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['risk_profile'] = df['avg_betting_odds'].apply(get_risk_profile)

risk_profile
1. Conservative (Low Odds)               3
2. Moderate (Medium Odds)             5511
3. High Risk / Dreamer (High Odds)    3065
Name: count, dtype: int64

In [ ]:
# Making sure there are no negative values ​​(the minimum is 0) and Handling extreme values ​​(Outliers)
df['betting_win_rate'] = df['betting_win_rate'].clip(lower=0.0, upper=1.0) # Making sure the ratios are in the correct range (0 to 1)

# Type casting (implicit type conversion)
df['betting_win_rate'] = df['betting_win_rate'] + 0.0 # Removing the (Negative Zero)

# Rounding betting_win_rate to 2 decimal places
df['betting_win_rate'] = df['betting_win_rate'].round(2)

# Grouping betting_win_rate into win_groups
def get_win_category(rate):
  if rate == 0.0:
    return '0. No Wins (0%)'
  elif rate <= 0.2:
    return '1. Low Win Rate (1-20%)'
  elif rate <= 0.5:
    return '2. Average (21-50%)'
  else:
    return '3. High Win Rate (>50%)'

# Creating a new column 'win_rate_segment' in the DataFrame 'df'
df['win_rate_segment'] = df['betting_win_rate'].apply(get_win_category)

# Checking the result (sample display)
print(df[['betting_win_rate', 'win_rate_segment']].sample(10))

# Checking the value counts of the 'win_rate_segment' column to see the distribution of win rate segments in the dataset
df['win_rate_segment'].value_counts().sort_index()

/tmp/ipykernel_427/400495747.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['betting_win_rate'] = df['betting_win_rate'].clip(lower=0.0, upper=1.0) # Making sure the ratios are in the correct range (0 to 1)
/tmp/ipykernel_427/400495747.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['betting_win_rate'] = df['betting_win_rate'] + 0.0 # Removing the (Negative Zero)

      betting_win_rate     win_rate_segment
275               0.33  2. Average (21-50%)
3756              0.46  2. Average (21-50%)
2475              0.46  2. Average (21-50%)
3206              0.24  2. Average (21-50%)
5480              0.26  2. Average (21-50%)
2851              0.44  2. Average (21-50%)
9378              0.43  2. Average (21-50%)
7486              0.43  2. Average (21-50%)
5084              0.32  2. Average (21-50%)
5048              0.32  2. Average (21-50%)

/tmp/ipykernel_427/400495747.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['betting_win_rate'] = df['betting_win_rate'].round(2)
/tmp/ipykernel_427/400495747.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['win_rate_segment'] = df['betting_win_rate'].apply(get_win_category)

win_rate_segment
0. No Wins (0%)               5
1. Low Win Rate (1-20%)     595
2. Average (21-50%)        7162
3. High Win Rate (>50%)     817
Name: count, dtype: int64

In [ ]:
# Checking 'total_stake_eur' col
df['calculated_total'] = df['bets_placed_total'] * df['avg_bet_amount_eur']

diff = (df['total_stake_eur'] - df['calculated_total']).abs()

print(f"Average difference between the original and calculated column: {diff.mean():.4f}")

Average difference between the original and calculated column: 83.5698

/tmp/ipykernel_427/774221866.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['calculated_total'] = df['bets_placed_total'] * df['avg_bet_amount_eur']

In [ ]:
# Removing the 'calculated_total' column from the DataFrame 'df'
df.drop(columns=['calculated_total'], errors='ignore', inplace=True)

# Type casting (implicit type conversion)
df['total_stake_eur'] = df['total_stake_eur'] + 0.0 # Removing the (Negative Zero)

# Rounding total_stake_eur to 2 decimal places
df['total_stake_eur'] = df['total_stake_eur'].round(2)

# Grouping total_stake_eur into stake_groups
def get_stake_tier(value):
  if value == 0.0:
    return '0. Zero Stake'
  elif value <= 100.0:
    return '1. Low (<100 eur)'
  elif value <= 1000.0:
    return '2. Medium (100-1k eur)'
  elif value <= 5000.0:
    return '3. High (1k-5k eur)'
  else:
    return '4. VIP / Whale (>5k eur)'

# Creating a new column 'stake_tier' in the DataFrame 'df'
df['stake_tier'] = df['total_stake_eur'].apply(get_stake_tier)

# Checking the result (sample display)
print(df[['total_stake_eur', 'stake_tier']].sample(10))

# Checking the value counts of the 'stake_tier' column to see the distribution of stake tiers in the dataset
df['stake_tier'].value_counts().sort_index()

      total_stake_eur                stake_tier
9065          1094.70       3. High (1k-5k eur)
7097           244.95    2. Medium (100-1k eur)
8111          3459.70       3. High (1k-5k eur)
1997           202.65    2. Medium (100-1k eur)
7890         13737.32  4. VIP / Whale (>5k eur)
9612          4901.55       3. High (1k-5k eur)
5852          2962.60       3. High (1k-5k eur)
3968          5499.80  4. VIP / Whale (>5k eur)
2520          2499.40       3. High (1k-5k eur)
4430          4023.80       3. High (1k-5k eur)

/tmp/ipykernel_427/917339087.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['calculated_total'], errors='ignore', inplace=True)
/tmp/ipykernel_427/917339087.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total_stake_eur'] = df['total_stake_eur'] + 0.0 # Removing the (Negative Zero)
/tmp/ipykernel_427/917339087.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total_stake_eur'] = df['total_stake_eur'].round(2)
/tmp/ipykernel_427/917339087.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['stake_tier'] = df['total_stake_eur'].apply(get_stake_tier)

stake_tier
0. Zero Stake                 76
1. Low (<100 eur)            350
2. Medium (100-1k eur)      2767
3. High (1k-5k eur)         4279
4. VIP / Whale (>5k eur)    1107
Name: count, dtype: int64

In [ ]:
# Type casting (implicit type conversion)
df['total_gain_eur'] = df['total_gain_eur'] + 0.0 # Removing the (Negative Zero)

# Rounding total_gain_eur to 2 decimal places
df['total_gain_eur'] = df['total_gain_eur'].round(2)

# Gruoping total_gain_eur into gain_groups
def get_gain_tier(gain):
  if gain == 0.0:
    return '0. Zero Gains'
  elif gain <= 500.0:
    return '1. Small Wins (<500)'
  elif gain <= 5000.0:
    return '2. Mid-Tier (500-5k)'
  elif gain <= 20000.0:
    return '3. Big Winners (5k-20k)'
  else:
    return '4. Jackpot Winners (>20k)'

# Creating a new column 'gain_segment' in the DataFrame 'df'
df['gain_segment'] = df['total_gain_eur'].apply(get_gain_tier)

# Checking the result (sample display)
print(df[['total_gain_eur', 'gain_segment']].sample(10))

# Checking the value counts of the 'gain_segment' column to see the distribution of gain segments in the dataset
df['gain_segment'].value_counts().sort_index()

      total_gain_eur             gain_segment
8677         2928.11     2. Mid-Tier (500-5k)
5138         8016.74  3. Big Winners (5k-20k)
925           184.56     1. Small Wins (<500)
804          2197.99     2. Mid-Tier (500-5k)
3002         5128.53  3. Big Winners (5k-20k)
9398          144.98     1. Small Wins (<500)
414          4291.86     2. Mid-Tier (500-5k)
9237         3200.89     2. Mid-Tier (500-5k)
2957          771.54     2. Mid-Tier (500-5k)
6540            0.00            0. Zero Gains

/tmp/ipykernel_427/4104291667.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total_gain_eur'] = df['total_gain_eur'] + 0.0 # Removing the (Negative Zero)
/tmp/ipykernel_427/4104291667.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total_gain_eur'] = df['total_gain_eur'].round(2)
/tmp/ipykernel_427/4104291667.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gain_segment'] = df['total_gain_eur'].apply(get_gain_tier)

gain_segment
0. Zero Gains                 117
1. Small Wins (<500)         2192
2. Mid-Tier (500-5k)         5188
3. Big Winners (5k-20k)      1028
4. Jackpot Winners (>20k)      54
Name: count, dtype: int64

In [ ]:
# Checking 'total_ggr' col
calculated_ggr = df['total_stake_eur'] - df['total_gain_eur']
diff = (df['total_ggr'] - calculated_ggr).abs()
print(f"Average difference in GGR: {diff.mean():.4f}")

Average difference in GGR: 168.8865

In [ ]:
# Removing the 'calculated_ggr' column from the DataFrame 'df'
df.drop(columns=['calculated_ggr'], errors='ignore', inplace=True)

# Rounding total_ggr to 2 decimal places
df['total_ggr'] = df['total_ggr'].round(2)

# Grouping total_ggr into ggr_groups
def get_ggr_segment(ggr):
  if ggr < -5000.0:
    return '1. Heavy Loss (VIP Winners) (< -5k)'
  elif ggr < 0.0:
    return '2. Net Winners (-5k to 0)'
  elif ggr == 0.0:
    return '3. Break-even'
  elif ggr <= 2000.0:
    return '4. Profitable (0 to 2k)'
  else:
    return '5. High Value (Whales) (> 2k)'

# Creating a new column 'ggr_segment' in the DataFrame 'df'
df['ggr_segment'] = df['total_ggr'].apply(get_ggr_segment)

# Checking the result (sample display)
print(df[['total_ggr', 'ggr_segment']].sample(10))

# Checking the value counts of the 'ggr_segment' column to see the distribution of GGR segments in the dataset
df['ggr_segment'].value_counts().sort_index()

/tmp/ipykernel_427/4157451748.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['calculated_ggr'], errors='ignore', inplace=True)
/tmp/ipykernel_427/4157451748.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total_ggr'] = df['total_ggr'].round(2)
/tmp/ipykernel_427/4157451748.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ggr_segment'] = df['total_ggr'].apply(get_ggr_segment)

      total_ggr                ggr_segment
7592     780.12    4. Profitable (0 to 2k)
5617    1444.51    4. Profitable (0 to 2k)
3035    -142.29  2. Net Winners (-5k to 0)
2089      11.28    4. Profitable (0 to 2k)
5481      84.80    4. Profitable (0 to 2k)
332      -40.10  2. Net Winners (-5k to 0)
6295       0.00              3. Break-even
7064     653.25    4. Profitable (0 to 2k)
6996       0.00              3. Break-even
3419       7.20    4. Profitable (0 to 2k)

ggr_segment
1. Heavy Loss (VIP Winners) (< -5k)      70
2. Net Winners (-5k to 0)              1910
3. Break-even                          1067
4. Profitable (0 to 2k)                4763
5. High Value (Whales) (> 2k)           769
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'favourite_sport' column to see the distribution of favourite sports in the dataset
df['favourite_sport'].value_counts()

favourite_sport
Football      8300
Tennis         251
Basketball      20
Ice Hockey       4
Handball         3
Snooker          1
Name: count, dtype: int64

In [ ]:
# Converting all text to a single case
df['preferred_bet_type'] = df['preferred_bet_type'].str.title()

# Checking the value counts of the 'preferred_bet_type' column to see the distribution of preferred bet types in the dataset
df['preferred_bet_type'].value_counts()

/tmp/ipykernel_427/2680356860.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['preferred_bet_type'] = df['preferred_bet_type'].str.title()

preferred_bet_type
Single      7721
Multiple     858
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'betting_enabled' column to see the distribution of bettings enabled in the dataset
df['betting_enabled'].value_counts()

betting_enabled
Yes    8579
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'responsible_gambling_flag' column to see the distribution of responsible gambling flags in the dataset
df['responsible_gambling_flag'].value_counts()

responsible_gambling_flag
No     7136
Yes    1443
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'betting_profile' column to see the distribution of betting profiles in the dataset
df['betting_profile'].value_counts()

betting_profile
Regular        7524
Casual          928
High-Roller     127
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'game_genre_preference' column to see the distribution of game genre preferences in the dataset
df['game_genre_preference'].value_counts()

game_genre_preference
Strategy      1781
Sports        1717
Simulation    1712
Action        1709
RPG           1660
Name: count, dtype: int64

In [ ]:
# Making sure there are no negative values (negative time) ​​(the minimum is 0)
df['gaming_playtime_hours_weekly'] = df['gaming_playtime_hours_weekly'].clip(lower=0.0)

# Casting type (implicit type conversion)
df['gaming_playtime_hours_weekly'] = df['gaming_playtime_hours_weekly'] + 0.0 # Removing the (Negative Zero)

# Rounding gaming_playtime_hours_weekly to 2 decimal places
df['gaming_playtime_hours_weekly'] = df['gaming_playtime_hours_weekly'].round(2)

# Grouping gaming_playtime_hours_weekly into playtime_groups
def get_playtime_segment(hours):
  if hours == 0.0:
    return '0. Inactive / Ghost'
  elif hours <= 2.0:
    return '1. Casual (<2 hrs)'
  elif hours <= 10.0:
    return '2. Regular (2-10 hrs)'
  else:
    return '3. Hardcore (>10 hrs)'

# Creating a new column 'playtime_segment' in the DataFrame 'df'
df['playtime_segment'] = df['gaming_playtime_hours_weekly'].apply(get_playtime_segment)

# Checking the result (sample display)
print(df[['gaming_playtime_hours_weekly', 'playtime_segment']].sample(10))

# Checking the value counts of the 'playtime_segment' column to see the distribution of playtime segments in the dataset
df['playtime_segment'].value_counts().sort_index()

/tmp/ipykernel_427/4194786155.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gaming_playtime_hours_weekly'] = df['gaming_playtime_hours_weekly'].clip(lower=0.0)
/tmp/ipykernel_427/4194786155.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gaming_playtime_hours_weekly'] = df['gaming_playtime_hours_weekly'] + 0.0 # Removing the (Negative Zero)
/tmp/ipykernel_427/4194786155.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gaming_playtime_hours_weekly'] = df['gaming_playtime_hours_weekly'].round(2)
/tmp/ipykernel_427/4194786155.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['playtime_segment'] = df['gaming_playtime_hours_weekly'].apply(get_playtime_segment)

       gaming_playtime_hours_weekly       playtime_segment
9199                          16.11  3. Hardcore (>10 hrs)
5940                           2.19  2. Regular (2-10 hrs)
1035                          22.46  3. Hardcore (>10 hrs)
2416                          19.10  3. Hardcore (>10 hrs)
3377                          19.46  3. Hardcore (>10 hrs)
3259                           2.65  2. Regular (2-10 hrs)
5736                          21.30  3. Hardcore (>10 hrs)
4190                          17.11  3. Hardcore (>10 hrs)
2644                          22.31  3. Hardcore (>10 hrs)
10289                          9.87  2. Regular (2-10 hrs)

playtime_segment
0. Inactive / Ghost        12
1. Casual (<2 hrs)        675
2. Regular (2-10 hrs)    2902
3. Hardcore (>10 hrs)    4990
Name: count, dtype: int64

In [ ]:
# Making sure there are no negative values ​​(the minimum is 0)
df['in_app_purchases_gaming'] = df['in_app_purchases_gaming'].clip(lower=0.0)

# Type casting (implicit type conversion)
df['in_app_purchases_gaming'] = df['in_app_purchases_gaming'] + 0.0 # Removing the (Negative Zero)

# Rounding in_app_purchases_gaming to 2 decimal places
df['in_app_purchases_gaming'] = df['in_app_purchases_gaming'].round(2)

# Grouping in_app_purchases_gaming into purchase_groups
def get_purchase_behavior(purchases):
  if purchases == 0.0:
    return '0. Non-Purchaser'
  elif purchases <= 0.5:
    return '1. Low Spender'
  else:
    return '2. Active Spender'

df['purchase_behavior'] = df['in_app_purchases_gaming'].apply(get_purchase_behavior)

# Checking the result (sample display)
print(df[['in_app_purchases_gaming', 'purchase_behavior']].sample(10))

# Checking the value counts of the 'purchase_behavior' column to see the distribution of purchase behaviors in the dataset
df['purchase_behavior'].value_counts().sort_index()

      in_app_purchases_gaming  purchase_behavior
7197                     0.01     1. Low Spender
871                      0.00   0. Non-Purchaser
7819                     0.00   0. Non-Purchaser
6863                     0.01     1. Low Spender
2677                     1.00  2. Active Spender
3847                     0.00   0. Non-Purchaser
2950                     0.00   0. Non-Purchaser
7479                     0.00   0. Non-Purchaser
6878                     0.01     1. Low Spender
4303                     0.00   0. Non-Purchaser

/tmp/ipykernel_427/1065794647.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['in_app_purchases_gaming'] = df['in_app_purchases_gaming'].clip(lower=0.0)
/tmp/ipykernel_427/1065794647.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['in_app_purchases_gaming'] = df['in_app_purchases_gaming'] + 0.0 # Removing the (Negative Zero)
/tmp/ipykernel_427/1065794647.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['in_app_purchases_gaming'] = df['in_app_purchases_gaming'].round(2)
/tmp/ipykernel_427/1065794647.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['purchase_behavior'] = df['in_app_purchases_gaming'].apply(get_purchase_behavior)

purchase_behavior
0. Non-Purchaser     5907
1. Low Spender        905
2. Active Spender    1767
Name: count, dtype: int64

In [ ]:
# Making sure there are no negative values ​(the minimum is 0)
df['gaming_sessions_per_week'] = df['gaming_sessions_per_week'].clip(lower=0.0)

# Type casting (implicit type conversion)
df['gaming_sessions_per_week'] = df['gaming_sessions_per_week'] + 0.0 # Removing the (Negative Zero)

# Rounding gaming_sessions_per_week to 2 decimal places
df['gaming_sessions_per_week'] = df['gaming_sessions_per_week'].round(2)

# Grouping gaming_sessions_per_week into session_groups
def get_session_intensity(sessions):
  if sessions == 0.0:
    return '0. Dormant (0 sessions)'
  elif sessions <= 1:
    return '1. Low (1-2 sessions)'
  elif sessions <= 7:
    return '2. Rare (<=1 session/week)'
  else:
    return '3. Heavy User (>7 sessions/week)'

# Creating a new column 'session_intensity' in the DataFrame 'df'
df['session_intensity'] = df['gaming_sessions_per_week'].apply(get_session_intensity)

# Checking the result (sample display)
print(df[['gaming_sessions_per_week', 'session_intensity']].sample(10))

# Checking the value counts of the 'session_intensity' column to see the distribution of session intensities in the dataset
df['session_intensity'].value_counts().sort_index()

/tmp/ipykernel_427/3106976401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gaming_sessions_per_week'] = df['gaming_sessions_per_week'].clip(lower=0.0)
/tmp/ipykernel_427/3106976401.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gaming_sessions_per_week'] = df['gaming_sessions_per_week'] + 0.0 # Removing the (Negative Zero)
/tmp/ipykernel_427/3106976401.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gaming_sessions_per_week'] = df['gaming_sessions_per_week'].round(2)

      gaming_sessions_per_week                 session_intensity
808                       9.00  3. Heavy User (>7 sessions/week)
40                        0.00           0. Dormant (0 sessions)
3892                      4.00        2. Rare (<=1 session/week)
415                      17.00  3. Heavy User (>7 sessions/week)
4266                     18.00  3. Heavy User (>7 sessions/week)
6431                     15.92  3. Heavy User (>7 sessions/week)
5692                     17.83  3. Heavy User (>7 sessions/week)
8325                      7.93  3. Heavy User (>7 sessions/week)
537                       1.00             1. Low (1-2 sessions)
3545                      3.00        2. Rare (<=1 session/week)

/tmp/ipykernel_427/3106976401.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['session_intensity'] = df['gaming_sessions_per_week'].apply(get_session_intensity)

session_intensity
0. Dormant (0 sessions)              358
1. Low (1-2 sessions)                460
2. Rare (<=1 session/week)          2630
3. Heavy User (>7 sessions/week)    5131
Name: count, dtype: int64

In [ ]:
# Making sure there are no negative values (negative time) ​​(the minimum is 0)
df['avg_gaming_session_mins'] = df['avg_gaming_session_mins'].clip(lower=0.0)

# Rounding avg_gaming_session_mins to 2 decimal places
df['avg_gaming_session_mins'] = df['avg_gaming_session_mins'].round(2)

# Grouping avg_gaming_session_mins into session_duration_groups
def get_session_duration(mins):
  if mins <= 10.0:
    return '1. Short (<10 mins)'
  elif mins <= 30.0:
    return '2. Moderate (10-30 mins)'
  elif mins <= 60.0:
    return '3. Long (30-60 mins)'
  else:
    return '4. Epic (>60 mins)'

# Creating a new column 'session_duration_tier' in the DataFrame 'df'
df['session_duration_tier'] = df['avg_gaming_session_mins'].apply(get_session_duration)

# Checking the result (sample display)
print(df[['avg_gaming_session_mins', 'session_duration_tier']].sample(10))

# Checking the value counts of the 'session_duration_tier' column to see the distribution of session duration tiers in the dataset
df['session_duration_tier'].value_counts().sort_index()

      avg_gaming_session_mins     session_duration_tier
7903                    72.00        4. Epic (>60 mins)
1870                    34.00      3. Long (30-60 mins)
5923                   152.00        4. Epic (>60 mins)
4448                   115.00        4. Epic (>60 mins)
4451                    80.00        4. Epic (>60 mins)
97                     141.00        4. Epic (>60 mins)
5805                    37.53      3. Long (30-60 mins)
5945                    25.55  2. Moderate (10-30 mins)
1587                   134.00        4. Epic (>60 mins)
6447                   115.81        4. Epic (>60 mins)

/tmp/ipykernel_427/3266287261.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['avg_gaming_session_mins'] = df['avg_gaming_session_mins'].clip(lower=0.0)
/tmp/ipykernel_427/3266287261.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['avg_gaming_session_mins'] = df['avg_gaming_session_mins'].round(2)
/tmp/ipykernel_427/3266287261.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['session_duration_tier'] = df['avg_gaming_session_mins'].apply(get_session_duration)

session_duration_tier
1. Short (<10 mins)           57
2. Moderate (10-30 mins)     979
3. Long (30-60 mins)        1527
4. Epic (>60 mins)          6016
Name: count, dtype: int64

In [ ]:
# Checkingg the value counts of the 'gaming_engagement_level' column to see the distribution of gaming engagement levels in the dataset
df['gaming_engagement_level'].value_counts()

gaming_engagement_level
Medium    4206
Low       2228
High      2145
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'ott_gaming_app_used' column to see the distribution of ott gaming app used in the dataset
df['ott_gaming_app_used'].value_counts()

ott_gaming_app_used
Yes    6351
No     2228
Name: count, dtype: int64

In [ ]:
# Removing extra spaces and convert all text to a single case (Lowercase)
df['acquisition_channel'] = df['acquisition_channel'].str.strip().str.lower()

# Creating a dictionary of monotheism
channel_map = {
    'email':'Email',
    'e-mail': 'Email',
    'pay-per-click': 'PPC',
    'ppc': 'PPC',
    'seo': 'SEO',
    'social media': 'Social Media',
    'social_media': 'Social Media'
}

# Applying the dictionary to the 'acquisition_channel' column
df['acquisition_channel'] = df['acquisition_channel'].map(channel_map).fillna(df['acquisition_channel'].str.title())

# Checking the result (sample display)
print(df['acquisition_channel'].sample(10))

# Checking the value counts of the 'acquisition_channel' column to see the distribution of acquisition channels in the dataset
df['acquisition_channel'].value_counts()

/tmp/ipykernel_427/4131500972.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['acquisition_channel'] = df['acquisition_channel'].str.strip().str.lower()
/tmp/ipykernel_427/4131500972.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['acquisition_channel'] = df['acquisition_channel'].map(channel_map).fillna(df['acquisition_channel'].str.title())

1969       Email
2999    Referral
7351         SEO
4704    Referral
3362    Referral
7159       Email
368        Email
2294       Email
4185         PPC
2985    Referral
Name: acquisition_channel, dtype: object

acquisition_channel
PPC             1816
Referral        1770
Email           1671
SEO             1662
Social Media    1660
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'acquisition_campaign_type' column to see the distribution of acquisition campaign types in the dataset
df['acquisition_campaign_type'].value_counts()

acquisition_campaign_type
Conversion       2208
Awareness        2142
Retention        2115
Consideration    2114
Name: count, dtype: int64

In [ ]:
# Type casting (implicit type conversion)
df['ad_spend_eur'] = df['ad_spend_eur'] + 0.0 # Removing the (Negative Zero)

# Rounding ad_spend_eur to 2 decimal places
df['ad_spend_eur'] = df['ad_spend_eur'].round(2)

# Grouping ad_spend_eur into spend_groups
def get_ad_spend_tier(spend):
  if spend < 0.0:
    return '1. Credited/Refunded'
  elif spend == 0.0:
    return '2. Organic (Free)'
  elif spend <= 100.0:
    return '3. Small Spend (<100 eur)'
  elif spend <= 1000.0:
    return '4. Medium Spend (100-1k eur)'
  elif spend <= 5000.0:
    return '5. Large Spend (1k-5k eur)'
  else:
    return '6. Institutional/VIP (>5k eur)'

# Creating a new column 'ad_spend_tier' in the DataFrame 'df'
df['ad_spend_tier'] = df['ad_spend_eur'].apply(get_ad_spend_tier)

# Checking the result (sample display)
print(df[['ad_spend_eur', 'ad_spend_tier']].sample(10))

# Checking the value counts of the 'ad_spend_tier' column to see the distribution of ad spend tiers in the dataset
df['ad_spend_tier'].value_counts().sort_index()

      ad_spend_eur                   ad_spend_tier
2343       9744.10  6. Institutional/VIP (>5k eur)
8885        524.67    4. Medium Spend (100-1k eur)
1453       9921.43  6. Institutional/VIP (>5k eur)
1723       1573.20      5. Large Spend (1k-5k eur)
2925       9376.59  6. Institutional/VIP (>5k eur)
4313       9736.68  6. Institutional/VIP (>5k eur)
621        9642.99  6. Institutional/VIP (>5k eur)
4907       4257.61      5. Large Spend (1k-5k eur)
6756       4163.44      5. Large Spend (1k-5k eur)
1422       6576.69  6. Institutional/VIP (>5k eur)

/tmp/ipykernel_427/1130270555.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ad_spend_eur'] = df['ad_spend_eur'] + 0.0 # Removing the (Negative Zero)
/tmp/ipykernel_427/1130270555.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ad_spend_eur'] = df['ad_spend_eur'].round(2)
/tmp/ipykernel_427/1130270555.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ad_spend_tier'] = df['ad_spend_eur'].apply(get_ad_spend_tier)

ad_spend_tier
1. Credited/Refunded                62
2. Organic (Free)                    9
3. Small Spend (<100 eur)           14
4. Medium Spend (100-1k eur)       753
5. Large Spend (1k-5k eur)        3520
6. Institutional/VIP (>5k eur)    4221
Name: count, dtype: int64

In [ ]:
# Ensuring that the percentage does not exceed 1 (100%) and is not less than 0
df['ctr'] = df['ctr'].clip(lower=0.0, upper=1.0)

# Type casting (implicit type conversion)
df['ctr'] = df['ctr'] + 0.0 # Removing the (Negative Zero)

# Rounding the ctr to 4 decimal places
df['ctr'] = df['ctr'].round(4)

# Grouping ctr into ctr_groups
def get_ctr_performance(ctr):
  if ctr <= 0.02:
    return '1. Low (<2%)'
  elif ctr <= 0.05:
    return '2. Average (2-5%)'
  elif ctr <= 0.15:
    return '3. High (5-15%)'
  else:
    return '4. Exceptional (>15%)'

# Creating a new column 'ctr_tier' in the DataFrame 'df'
df['ctr_tier'] = df['ctr'].apply(get_ctr_performance)

# Checking the result (sample display)
print(df[['ctr', 'ctr_tier']].sample(10))

# Checking the value counts of the 'ctr_tier' column to see the distribution of CTR tiers in the dataset
df['ctr_tier'].value_counts().sort_index()

         ctr               ctr_tier
7080  0.1400        3. High (5-15%)
524   0.1417        3. High (5-15%)
3917  0.1839  4. Exceptional (>15%)
1917  0.1806  4. Exceptional (>15%)
5942  0.2900  4. Exceptional (>15%)
4021  0.0252      2. Average (2-5%)
1560  0.0453      2. Average (2-5%)
5409  0.0100           1. Low (<2%)
4516  0.2550  4. Exceptional (>15%)
1409  0.1943  4. Exceptional (>15%)

/tmp/ipykernel_427/1192762488.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ctr'] = df['ctr'].clip(lower=0.0, upper=1.0)
/tmp/ipykernel_427/1192762488.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ctr'] = df['ctr'] + 0.0 # Removing the (Negative Zero)
/tmp/ipykernel_427/1192762488.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ctr'] = df['ctr'].round(4)
/tmp/ipykernel_427/1192762488.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ctr_tier'] = df['ctr'].apply(get_ctr_performance)

ctr_tier
1. Low (<2%)              339
2. Average (2-5%)         908
3. High (5-15%)          3011
4. Exceptional (>15%)    4321
Name: count, dtype: int64

In [ ]:
# Ensuring that the percentage does not exceed 1 (100%) and is not less than 0
df['conversion_rate'] = df['conversion_rate'].clip(lower=0.0, upper=1.0)

# Type casting (implicit type conversion)
df['conversion_rate'] = df['conversion_rate'] + 0.0 # Removing the (Negative Zero)

# Rounding the conversion_rate to 4 decimal places
df['conversion_rate'] = df['conversion_rate'].round(4)

# Grouping conversion_rate into conversion_groups
def get_conversion_tier(conversion):
  if conversion <= 0.02:
    return '1. Standard (<2%)'
  elif conversion <= 0.05:
    return '2. Healthy (2-5%)'
  elif conversion <= 0.10:
    return '3. High (5-10%)'
  else:
    return '4. Top Tier (>10%)'

# Creating a new column 'conversion_tier' in the DataFrame 'df'
df['conversion_tier'] = df['conversion_rate'].apply(get_conversion_tier)

# Checking the result (sample display)
print(df[['conversion_rate', 'conversion_tier']].sample(10))

# Checking the value counts of the 'conversion_tier' column to see the distribution of conversion tiers in the dataset
df['conversion_tier'].value_counts().sort_index()

      conversion_rate     conversion_tier
4474           0.0429   2. Healthy (2-5%)
7302           0.0700     3. High (5-10%)
1730           0.0372   2. Healthy (2-5%)
3530           0.1530  4. Top Tier (>10%)
3077           0.1094  4. Top Tier (>10%)
6170           0.1300  4. Top Tier (>10%)
4768           0.1612  4. Top Tier (>10%)
4172           0.0993     3. High (5-10%)
5969           0.0400   2. Healthy (2-5%)
5458           0.0200   1. Standard (<2%)

/tmp/ipykernel_427/2615550413.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['conversion_rate'] = df['conversion_rate'].clip(lower=0.0, upper=1.0)
/tmp/ipykernel_427/2615550413.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['conversion_rate'] = df['conversion_rate'] + 0.0 # Removing the (Negative Zero)
/tmp/ipykernel_427/2615550413.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['conversion_rate'] = df['conversion_rate'].round(4)
/tmp/ipykernel_427/2615550413.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['conversion_tier'] = df['conversion_rate'].apply(get_conversion_tier)

conversion_tier
1. Standard (<2%)      553
2. Healthy (2-5%)     1400
3. High (5-10%)       2269
4. Top Tier (>10%)    4357
Name: count, dtype: int64

In [ ]:
# Making sure there are no negative values (negative time) ​​(the minimum is 0)
df['time_on_site_mins'] = df['time_on_site_mins'].clip(lower=0.0)

# Type casting (implicit type conversion)
df['time_on_site_mins'] = df['time_on_site_mins'] + 0.0 # Removing the (Negative Zero)

# Rounding time_on_site_mins to 2 decimal places
df['time_on_site_mins'] = df['time_on_site_mins'].round(2)

# Grouping time_on_site_mins into site_engagement_groups
def get_site_engagement(mins):
  if mins <= 2.0:
    return '1. Bouncer (<2 mins)'
  elif mins <= 5.0:
    return '2. Average (2-5 mins)'
  else:
    return '3. Engaged (>7 mins)'

# Creating a new column 'site_engagement_tier' in the DataFrame 'df'
df['site_engagement_tier'] = df['time_on_site_mins'].apply(get_site_engagement)

# Checking the result (sample display)
print(df[['time_on_site_mins', 'site_engagement_tier']].sample(10))

# Checking the value counts of the 'site_engagement_tier' column to see the distribution of site engagement tiers in the dataset
df['site_engagement_tier'].value_counts().sort_index()

/tmp/ipykernel_427/4258369861.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['time_on_site_mins'] = df['time_on_site_mins'].clip(lower=0.0)
/tmp/ipykernel_427/4258369861.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['time_on_site_mins'] = df['time_on_site_mins'] + 0.0 # Removing the (Negative Zero)
/tmp/ipykernel_427/4258369861.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['time_on_site_mins'] = df['time_on_site_mins'].round(2)
/tmp/ipykernel_427/4258369861.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['site_engagement_tier'] = df['time_on_site_mins'].apply(get_site_engagement)

      time_on_site_mins   site_engagement_tier
194                1.92   1. Bouncer (<2 mins)
7388               1.31   1. Bouncer (<2 mins)
895                7.74   3. Engaged (>7 mins)
2516               2.31  2. Average (2-5 mins)
250               12.37   3. Engaged (>7 mins)
3886               8.02   3. Engaged (>7 mins)
5872              13.80   3. Engaged (>7 mins)
6381              11.90   3. Engaged (>7 mins)
4700              10.82   3. Engaged (>7 mins)
5155              12.11   3. Engaged (>7 mins)

site_engagement_tier
1. Bouncer (<2 mins)      948
2. Average (2-5 mins)    1704
3. Engaged (>7 mins)     5927
Name: count, dtype: int64

In [ ]:
# Making sure there are no negative values ​​(the minimum is 0)
df['loyalty_points'] = df['loyalty_points'].clip(lower=0)

# Rounding loyalty_points_earned to the nearest integer
df['loyalty_points'] = df['loyalty_points'].round(0).astype(int)

# Grouping loyalty_points_earned into loyalty_groups
def get_loyalty_tier(points):
  if points <= 500:
    return '1. Bronze (0-500)'
  elif points <= 1500:
    return '2. Silver (500-1.5k)'
  elif points <= 3000:
    return '3. Gold (1.5k-3k)'
  else:
    return '4. Platinum (>3k)'

# Creating a new column 'loyalty_tier' in the DataFrame 'df'
df['loyalty_tier'] = df['loyalty_points'].apply(get_loyalty_tier)

# Checking the result (sample display)
print(df[['loyalty_points', 'loyalty_tier']].sample(10))

# Checking the value counts of the 'loyalty_tier' column to see the distribution of loyalty tiers in the dataset
df['loyalty_tier'].value_counts().sort_index()

      loyalty_points          loyalty_tier
5598              41     1. Bronze (0-500)
4215             893  2. Silver (500-1.5k)
3625            1643     3. Gold (1.5k-3k)
71              3769     4. Platinum (>3k)
7634            3568     4. Platinum (>3k)
2536            3223     4. Platinum (>3k)
4829            3223     4. Platinum (>3k)
2304            3537     4. Platinum (>3k)
6609            3049     4. Platinum (>3k)
7442             413     1. Bronze (0-500)

/tmp/ipykernel_427/1267944468.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['loyalty_points'] = df['loyalty_points'].clip(lower=0)
/tmp/ipykernel_427/1267944468.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['loyalty_points'] = df['loyalty_points'].round(0).astype(int)
/tmp/ipykernel_427/1267944468.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['loyalty_tier'] = df['loyalty_points'].apply(get_loyalty_tier)

loyalty_tier
1. Bronze (0-500)        827
2. Silver (500-1.5k)    1725
3. Gold (1.5k-3k)       2536
4. Platinum (>3k)       3491
Name: count, dtype: int64

In [ ]:
# Making sure there are no negative values ​​(the minimum is 0)
df['roas'] = df['roas'].clip(lower=0.0)

# Rounding roas to 2 decimal places
df['roas'] = df['roas'].round(2)

# Grouping roas into roas_groups
def get_roas_tier(roas):
  if roas == 0.0:
    return '0. No Return (0)'
  elif roas <= 1.0:
    return '1. Loss (<1x)'
  elif roas <= 3.0:
    return '2. Breakeven/Low (1-3x)'
  elif roas <= 10.0:
    return '3. Healthy (3-10x)'
  else:
    return '4. High Performance (>10x)'

# Creating a new column 'roas_segment' in the DataFrame 'df'
df['roas_segment'] = df['roas'].apply(get_roas_tier)

# Checking the result (sample display)
print(df[['roas', 'roas_segment']].sample(10))

# Checking the value counts of the 'roas_segment' column to see the distribution of ROAS segments in the dataset
df['roas_segment'].value_counts().sort_index()

/tmp/ipykernel_427/1936107972.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['roas'] = df['roas'].clip(lower=0.0)
/tmp/ipykernel_427/1936107972.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['roas'] = df['roas'].round(2)
/tmp/ipykernel_427/1936107972.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['roas_segment'] = df['roas'].apply(get_roas_tier)

        roas                roas_segment
2543   53.24  4. High Performance (>10x)
9533  258.49  4. High Performance (>10x)
8091  422.74  4. High Performance (>10x)
2502   77.05  4. High Performance (>10x)
9750  409.71  4. High Performance (>10x)
4980  381.06  4. High Performance (>10x)
2659  229.01  4. High Performance (>10x)
960    40.00  4. High Performance (>10x)
22    265.28  4. High Performance (>10x)
3173  285.99  4. High Performance (>10x)

roas_segment
0. No Return (0)                18
1. Loss (<1x)                   15
2. Breakeven/Low (1-3x)         39
3. Healthy (3-10x)             136
4. High Performance (>10x)    8371
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'used_free_trial' column to see the distribution of used free trials in the dataset
df['used_free_trial'].value_counts()

used_free_trial
Yes    4606
No     3973
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'promo_discount_applied' column to see the distribution of promo discount applied in the dataset
df['promo_discount_applied'].value_counts()

promo_discount_applied
No     5589
Yes    2990
Name: count, dtype: int64

In [ ]:
# Fillng the missing values in the 'avg_session_duration_mins' column with median
df['avg_session_duration_mins'] = df['avg_session_duration_mins'].fillna(df['avg_session_duration_mins'].median())

# Making sure there are no negative values (negative time) ​(the minimum is 0) and Handling extreme values ​​(Outliers)
df['avg_session_duration_mins'] = df['avg_session_duration_mins'].clip(lower=0.0, upper=1440.0)

# Rounding avg_session_duration_mins to 2 decimal places
df['avg_session_duration_mins'] = df['avg_session_duration_mins'].round(2)

# Grouping avg_session_duration_mins into session_duration_groups
def get_session_duration(mins):
  if mins <= 5.0:
    return '1. Short/Bounce (<5m)'
  elif mins <= 30.0:
    return '2. Standard (5-30m)'
  elif mins <= 120.0:
    return '3. Engaged (30m-2h)'
  elif mins <= 480.0:
    return '4. Heavy User (2-8h)'
  else:
    return '5. Extreme/Possible Error (>8h)'

# Creating a new column 'session_duration_segment' in the DataFrame 'df'
df['session_duration_segment'] = df['avg_session_duration_mins'].apply(get_session_duration)

# Checking the result (sample display)
print(df[['avg_session_duration_mins', 'session_duration_segment']].sample(10))

# Checking the value counts of the 'session_duration_segment' column to see the distribution of session duration segments in the dataset
df['session_duration_segment'].value_counts().sort_index()

      avg_session_duration_mins session_duration_segment
5071                     200.00     4. Heavy User (2-8h)
239                       46.60      3. Engaged (30m-2h)
1831                     146.40     4. Heavy User (2-8h)
7475                     205.17     4. Heavy User (2-8h)
4797                     189.00     4. Heavy User (2-8h)
3210                      42.70      3. Engaged (30m-2h)
6788                     211.68     4. Heavy User (2-8h)
5914                      31.97      3. Engaged (30m-2h)
5954                     122.21     4. Heavy User (2-8h)
1252                      32.60      3. Engaged (30m-2h)

/tmp/ipykernel_427/3529925386.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['avg_session_duration_mins'] = df['avg_session_duration_mins'].fillna(df['avg_session_duration_mins'].median())
/tmp/ipykernel_427/3529925386.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['avg_session_duration_mins'] = df['avg_session_duration_mins'].clip(lower=0.0, upper=1440.0)
/tmp/ipykernel_427/3529925386.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['avg_session_duration_mins'] = df['avg_session_duration_mins'].round(2)
/tmp/ipykernel_427/3529925386.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['session_duration_segment'] = df['avg_session_duration_mins'].apply(get_session_duration)

session_duration_segment
1. Short/Bounce (<5m)                25
2. Standard (5-30m)                 899
3. Engaged (30m-2h)                3160
4. Heavy User (2-8h)               4460
5. Extreme/Possible Error (>8h)      35
Name: count, dtype: int64

In [ ]:
# Handling extreme values ​​(Outliers) making sure (two titles per day) as a reasonable limit for normal human consumption
df['titles_watched_per_month'] = df['titles_watched_per_month'].clip(upper=60.0)

# Rounding titles_watched_per_month to 2 decimal places
df['titles_watched_per_month'] = df['titles_watched_per_month'].round(2)

# Grouping titles_watched_per_month into titles_watched_groups
def get_viewer_segment(titles):
  if titles == 0.0:
    return '0. Inactive (0)'
  elif titles <= 1.0:
    return '1. Occasional (<1)'
  elif titles <= 5.0:
    return '2. Regular (1-5)'
  elif titles <= 20.0:
    return '3. Active (5-20)'
  else:
    return '4. Super Viewer (>20)'

# Creating a new column 'viewer_segment' in the DataFrame 'df'
df['viewer_segment'] = df['titles_watched_per_month'].apply(get_viewer_segment)

# Checking the result (sample display)
print(df[['titles_watched_per_month', 'viewer_segment']].sample(10))

# Checking the value counts of the 'viewer_segment' column to see the distribution of viewer segments in the dataset
df['viewer_segment'].value_counts().sort_index()

/tmp/ipykernel_427/810035994.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['titles_watched_per_month'] = df['titles_watched_per_month'].clip(upper=60.0)
/tmp/ipykernel_427/810035994.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['titles_watched_per_month'] = df['titles_watched_per_month'].round(2)
/tmp/ipykernel_427/810035994.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['viewer_segment'] = df['titles_watched_per_month'].apply(get_viewer_segment)

       titles_watched_per_month         viewer_segment
4833                       9.00       3. Active (5-20)
4693                      42.00  4. Super Viewer (>20)
10015                     26.00  4. Super Viewer (>20)
995                       51.00  4. Super Viewer (>20)
1454                      60.00  4. Super Viewer (>20)
1261                      19.00       3. Active (5-20)
4931                       5.00       2. Regular (1-5)
6453                      60.00  4. Super Viewer (>20)
6741                      60.00  4. Super Viewer (>20)
6249                      17.67       3. Active (5-20)

viewer_segment
0. Inactive (0)            86
1. Occasional (<1)        110
2. Regular (1-5)          416
3. Active (5-20)         1598
4. Super Viewer (>20)    6369
Name: count, dtype: int64

In [ ]:
# Ensuring that the percentage does not exceed 1 (100%)
df['series_completion_rate'] = df['series_completion_rate'].clip(upper=1.0)

# Rounding series_completion_rate to 4 decimal places
df['series_completion_rate'] = df['series_completion_rate'].round(4)

# Grouping series_completion_rate into completion_groups
def get_completion_segment(rate):
  if rate == 0.0:
    return '0. Non-Starter (0%)'
  elif rate <= 0.20:
    return '2. Low/Sampler (<20%)'
  elif rate <= 0.60:
    return '3. Moderate (20-60%)'
  elif rate < 1.0:
    return '4. High Finisher (60-99%)'
  else:
    return '5. Perfect Completion (100%)'

# Creating a new column 'completion_segment' in the DataFrame 'df'
df['completion_segment'] = df['series_completion_rate'].apply(get_completion_segment)

# Checking the result (sample display)
print(df[['series_completion_rate', 'completion_segment']].sample(10))

# Checking the value counts of the 'completion_segment' column to see the distribution of completion segments in the dataset
df['completion_segment'].value_counts().sort_index()

      series_completion_rate         completion_segment
7195                    0.50       3. Moderate (20-60%)
6651                    0.72  4. High Finisher (60-99%)
3075                    0.98  4. High Finisher (60-99%)
6221                    0.99  4. High Finisher (60-99%)
4099                    0.36       3. Moderate (20-60%)
4599                    0.42       3. Moderate (20-60%)
4838                    0.40       3. Moderate (20-60%)
7982                    0.10      2. Low/Sampler (<20%)
7419                    0.57       3. Moderate (20-60%)
4643                    0.85  4. High Finisher (60-99%)

/tmp/ipykernel_427/821661003.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['series_completion_rate'] = df['series_completion_rate'].clip(upper=1.0)
/tmp/ipykernel_427/821661003.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['series_completion_rate'] = df['series_completion_rate'].round(4)
/tmp/ipykernel_427/821661003.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['completion_segment'] = df['series_completion_rate'].apply(get_completion_segment)

completion_segment
0. Non-Starter (0%)               59
2. Low/Sampler (<20%)           1675
3. Moderate (20-60%)            3544
4. High Finisher (60-99%)       3251
5. Perfect Completion (100%)      50
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'content_genre_preference' column to see the distribution of content genre preferences in the dataset
df['content_genre_preference'].value_counts()

content_genre_preference
Drama          1845
Thriller       1479
Reality        1352
Kids           1207
Comedy         1056
Documentary     975
News            665
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'peak_viewing_hour' column to see the distribution of peak viewing hours in the dataset
df['peak_viewing_hour'].value_counts()

peak_viewing_hour
Evening       4727
Late Night    1808
Afternoon     1208
Morning        836
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'primary_device' column to see the distribution of primary devices in the dataset
df['primary_device'].value_counts()

primary_device
Smart TV    3484
Mobile      2658
Tablet      1118
Desktop      757
Console      562
Name: count, dtype: int64

In [ ]:
# Handling extreme values ​​(Outliers) making sure (six devices per subscriber) as a logical maximum for most subscriptions
df['num_devices_registered'] = df['num_devices_registered'].clip(upper=6)

# Rounding num_devices_registered to the nearest integer
df['num_devices_registered'] = df['num_devices_registered'].round(0).astype(int)

# Grouping num_devices_registered into device_segment
def get_device_segment(devices):
  if devices <= 1:
    return '1. Single Device'
  elif devices <= 3:
    return '2. Multi-Device (2-3)'
  else:
    return '3. Power User/Sharing (>3)'

# Creating a new column 'device_segment' in the DataFrame 'df'
df['device_segment'] = df['num_devices_registered'].apply(get_device_segment)

# Checking the result (sample display)
print(df[['num_devices_registered', 'device_segment']].sample(10))

# Checking the value counts of the 'device_segment' column to see the distribution of device segments in the dataset
df['device_segment'].value_counts().sort_index()

      num_devices_registered              device_segment
7113                       5  3. Power User/Sharing (>3)
5299                       1            1. Single Device
1093                       6  3. Power User/Sharing (>3)
626                        5  3. Power User/Sharing (>3)
7445                       1            1. Single Device
8819                       5  3. Power User/Sharing (>3)
4097                       4  3. Power User/Sharing (>3)
8115                       1            1. Single Device
7574                       3       2. Multi-Device (2-3)
5881                       3       2. Multi-Device (2-3)

/tmp/ipykernel_427/629084820.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_devices_registered'] = df['num_devices_registered'].clip(upper=6)
/tmp/ipykernel_427/629084820.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_devices_registered'] = df['num_devices_registered'].round(0).astype(int)
/tmp/ipykernel_427/629084820.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['device_segment'] = df['num_devices_registered'].apply(get_device_segment)

device_segment
1. Single Device              1424
2. Multi-Device (2-3)         2769
3. Power User/Sharing (>3)    4386
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'download_feature_used' column to see the distribution of download feature used in the dataset
df['download_feature_used'].value_counts()

download_feature_used
No     6129
Yes    2450
Name: count, dtype: int64

In [ ]:
# Ensuring that the percentage does not exceed 1 (100%)
df['live_to_vod_ratio'] = df['live_to_vod_ratio'].clip(upper=1.0)

# Rounding live_to_vod_ratio to 4 decimal places
df['live_to_vod_ratio'] = df['live_to_vod_ratio'].round(4)

# Grouping live_to_vod_ratio into ratio_groups
def get_content_preference(content):
  if content == 0.0:
    return '0. Pure VOD (0%)'
  elif content <= 0.30:
    return '1. VOD Leaning (1-30%)'
  elif content <= 0.70:
    return '2. Balanced Hybrid (30-70%)'
  else:
    return '3. Live Enthusiast (>70%)'

# Creating a new column 'content_preference_segment' in the DataFrame 'df'
df['content_preference_segment'] = df['live_to_vod_ratio'].apply(get_content_preference)

# Checking the result (sample display)
print(df[['live_to_vod_ratio', 'content_preference_segment']].sample(10))

# Checking the value counts of the 'content_preference_segment' column to see the distribution of content preference segments in the dataset
df['content_preference_segment'].value_counts().sort_index()

/tmp/ipykernel_427/2183190054.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['live_to_vod_ratio'] = df['live_to_vod_ratio'].clip(upper=1.0)
/tmp/ipykernel_427/2183190054.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['live_to_vod_ratio'] = df['live_to_vod_ratio'].round(4)
/tmp/ipykernel_427/2183190054.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['content_preference_segment'] = df['live_to_vod_ratio'].apply(get_content_preference)

      live_to_vod_ratio   content_preference_segment
4925               0.27       1. VOD Leaning (1-30%)
4132               0.28       1. VOD Leaning (1-30%)
943                0.06       1. VOD Leaning (1-30%)
5463               0.48  2. Balanced Hybrid (30-70%)
559                0.22       1. VOD Leaning (1-30%)
1258               0.29       1. VOD Leaning (1-30%)
1116               0.99    3. Live Enthusiast (>70%)
2478               0.10       1. VOD Leaning (1-30%)
5795               0.06       1. VOD Leaning (1-30%)
5404               0.65  2. Balanced Hybrid (30-70%)

content_preference_segment
0. Pure VOD (0%)                 51
1. VOD Leaning (1-30%)         2587
2. Balanced Hybrid (30-70%)    3422
3. Live Enthusiast (>70%)      2519
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'subscription_plan' column to see the distribution of subscription plans in the dataset
df['subscription_plan'].value_counts()

subscription_plan
Standard    2970
Basic       2198
Premium     2127
Family      1284
Name: count, dtype: int64

In [ ]:
# Handling extreme values ​​(Outliers) making sure (the maximum is 3) as any value above 3 is considered a critical failure and is equally dangerous
df['payment_failures'] = df['payment_failures'].clip(upper=3.0)

# Rounding payment_failures to 2 decimal places
df['payment_failures'] = df['payment_failures'].round(2)

# Grouping payment_failures into failure_groups
def get_payment_risk_tier(failure):
  if failure == 0.0:
    return '0. No Risk (0)'
  elif failure <= 0.5:
    return '1. Low Friction (<0.5)'
  elif failure <= 1.0:
    return '2. Moderate Risk (0.5-1)'
  else:
    return '3. Critical Risk (>1)'

# Creating a new column 'payment_risk_segment' in the DataFrame 'df'
df['payment_risk_segment'] = df['payment_failures'].apply(get_payment_risk_tier)

# Checking the result (sample display)
print(df[['payment_failures', 'payment_risk_segment']].sample(10))

# Checking the value counts of the 'payment_risk_segment' column to see the distribution of payment risk segments in the dataset
df['payment_risk_segment'].value_counts().sort_index()

/tmp/ipykernel_427/1493646577.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['payment_failures'] = df['payment_failures'].clip(upper=3.0)

      payment_failures    payment_risk_segment
6946              0.00          0. No Risk (0)
1926              0.00          0. No Risk (0)
3413              2.00   3. Critical Risk (>1)
7038              0.00          0. No Risk (0)
7366              0.08  1. Low Friction (<0.5)
5804              0.06  1. Low Friction (<0.5)
1158              0.00          0. No Risk (0)
2923              0.00          0. No Risk (0)
5397              0.01  1. Low Friction (<0.5)
1392              2.00   3. Critical Risk (>1)

/tmp/ipykernel_427/1493646577.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['payment_failures'] = df['payment_failures'].round(2)
/tmp/ipykernel_427/1493646577.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['payment_risk_segment'] = df['payment_failures'].apply(get_payment_risk_tier)

payment_risk_segment
0. No Risk (0)              5870
1. Low Friction (<0.5)      1012
2. Moderate Risk (0.5-1)     873
3. Critical Risk (>1)        824
Name: count, dtype: int64

In [ ]:
# Checking the value counts of the 'plan_change_history' column to see the distribution of plan changes in the dataset
df['plan_change_history'].value_counts()

plan_change_history
No Change     5561
Upgraded      1736
Downgraded    1282
Name: count, dtype: int64

In [ ]:
# Removing the 'data_source' column from the DataFrame 'df'
df.drop(columns=['data_source'], errors='ignore', inplace=True)

/tmp/ipykernel_427/2916982927.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['data_source'], errors='ignore', inplace=True)

In [ ]:
df

,subscriber_id,age,gender,subscription_tenure_months,region,payment_method,support_tickets_raised,satisfaction_score,promo_discount_pct,days_since_last_activity,...,conversion_tier,site_engagement_tier,loyalty_tier,roas_segment,session_duration_segment,viewer_segment,completion_segment,device_segment,content_preference_segment,payment_risk_segment
0,SUB-00001,56,Male,54.00,LATAM,PayPal,0,9,6.42,319.00,...,2. Healthy (2-5%),3. Engaged (>7 mins),1. Bronze (0-500),4. High Performance (>10x),3. Engaged (30m-2h),4. Super Viewer (>20),3. Moderate (20-60%),3. Power User/Sharing (>3),3. Live Enthusiast (>70%),0. No Risk (0)
1,SUB-00002,69,Female,21.00,APAC,Debit Card,1,2,13.77,166.00,...,4. Top Tier (>10%),3. Engaged (>7 mins),3. Gold (1.5k-3k),4. High Performance (>10x),4. Heavy User (2-8h),4. Super Viewer (>20),3. Moderate (20-60%),2. Multi-Device (2-3),2. Balanced Hybrid (30-70%),2. Moderate Risk (0.5-1)
2,SUB-00003,46,Female,49.00,APAC,PayPal,3,8,19.91,207.00,...,2. Healthy (2-5%),3. Engaged (>7 mins),2. Silver (500-1.5k),4. High Performance (>10x),4. Heavy User (2-8h),4. Super Viewer (>20),3. Moderate (20-60%),3. Power User/Sharing (>3),2. Balanced Hybrid (30-70%),3. Critical Risk (>1)
3,SUB-00004,32,Male,47.00,AMER,Debit Card,3,1,13.39,108.00,...,3. High (5-10%),3. Engaged (>7 mins),3. Gold (1.5k-3k),4. High Performance (>10x),4. Heavy User (2-8h),3. Active (5-20),3. Moderate (20-60%),3. Power User/Sharing (>3),3. Live Enthusiast (>70%),0. No Risk (0)
4,SUB-00005,60,Male,6.00,APAC,Credit Card,2,6,13.18,65.00,...,4. Top Tier (>10%),1. Bouncer (<2 mins),1. Bronze (0-500),4. High Performance (>10x),3. Engaged (30m-2h),2. Regular (1-5),2. Low/Sampler (<20%),3. Power User/Sharing (>3),2. Balanced Hybrid (30-70%),0. No Risk (0)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10249,SUB-10250,47,Male,43.71,AMER,PayPal,2,8,13.78,331.03,...,4. Top Tier (>10%),3. Engaged (>7 mins),3. Gold (1.5k-3k),4. High Performance (>10x),3. Engaged (30m-2h),4. Super Viewer (>20),4. High Finisher (60-99%),3. Power User/Sharing (>3),2. Balanced Hybrid (30-70%),0. No Risk (0)
10261,SUB-10262,55,Female,14.00,EMEA,PayPal,4,8,18.20,71.00,...,2. Healthy (2-5%),3. Engaged (>7 mins),2. Silver (500-1.5k),4. High Performance (>10x),4. Heavy User (2-8h),4. Super Viewer (>20),4. High Finisher (60-99%),2. Multi-Device (2-3),3. Live Enthusiast (>70%),3. Critical Risk (>1)
10262,SUB-10263,24,Female,17.79,AMER,Credit Card,3,3,15.74,338.35,...,4. Top Tier (>10%),3. Engaged (>7 mins),3. Gold (1.5k-3k),4. High Performance (>10x),3. Engaged (30m-2h),4. Super Viewer (>20),3. Moderate (20-60%),3. Power User/Sharing (>3),2. Balanced Hybrid (30-70%),0. No Risk (0)
10287,SUB-10288,67,Female,47.89,LATAM,PayPal,2,4,8.88,24.28,...,4. Top Tier (>10%),3. Engaged (>7 mins),2. Silver (500-1.5k),4. High Performance (>10x),4. Heavy User (2-8h),4. Super Viewer (>20),3. Moderate (20-60%),2. Multi-Device (2-3),1. VOD Leaning (1-30%),0. No Risk (0)
10289,SUB-10290,29,Female,31.06,EMEA,PayPal,1,3,19.91,14.99,...,4. Top Tier (>10%),3. Engaged (>7 mins),2. Silver (500-1.5k),4. High Performance (>10x),4. Heavy User (2-8h),4. Super Viewer (>20),3. Moderate (20-60%),3. Power User/Sharing (>3),1. VOD Leaning (1-30%),1. Low Friction (<0.5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8579 entries, 0 to 10289
Data columns (total 90 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   subscriber_id                 8579 non-null   object
 1   age                           8579 non-null   int64
 2   gender                        8579 non-null   object
 3   subscription_tenure_months    8579 non-null   float64
 4   region                        8579 non-null   object
 5   payment_method                8579 non-null   object
 6   support_tickets_raised        8579 non-null   int64
 7   satisfaction_score            8579 non-null   int64
 8   promo_discount_pct            8579 non-null   float64
 9   days_since_last_activity      8579 non-null   float64
 10  monthly_spend_eur             8579 non-null   float64
 11  churn                         8579 non-null   int64
 12  live_sports_subscriber        8579 non-null   object
 13  sports_events_watched_month   8579 non-null   int64
 14  favourite_live_sport          8579 non-null   object
 15  live_event_spike_signup       8579 non-null   object
 16  stream_quality_preference     8579 non-null   object
 17  bets_placed_total             8579 non-null   int64
 18  avg_bet_amount_eur            8579 non-null   float64
 19  avg_betting_odds              8579 non-null   float64
 20  betting_win_rate              8579 non-null   float64
 21  total_stake_eur               8579 non-null   float64
 22  total_gain_eur                8579 non-null   float64
 23  total_ggr                     8579 non-null   float64
 24  favourite_sport               8579 non-null   object
 25  preferred_bet_type            8579 non-null   object
 26  betting_enabled               8579 non-null   object
 27  responsible_gambling_flag     8579 non-null   object
 28  betting_profile               8579 non-null   object
 29  game_genre_preference         8579 non-null   object
 30  gaming_playtime_hours_weekly  8579 non-null   float64
 31  in_app_purchases_gaming       8579 non-null   float64
 32  gaming_sessions_per_week      8579 non-null   float64
 33  avg_gaming_session_mins       8579 non-null   float64
 34  gaming_engagement_level       8579 non-null   object
 35  ott_gaming_app_used           8579 non-null   object
 36  acquisition_channel           8579 non-null   object
 37  acquisition_campaign_type     8579 non-null   object
 38  ad_spend_eur                  8579 non-null   float64
 39  ctr                           8579 non-null   float64
 40  conversion_rate               8579 non-null   float64
 41  time_on_site_mins             8579 non-null   float64
 42  loyalty_points                8579 non-null   int64
 43  roas                          8579 non-null   float64
 44  used_free_trial               8579 non-null   object
 45  promo_discount_applied        8579 non-null   object
 46  avg_session_duration_mins     8579 non-null   float64
 47  titles_watched_per_month      8579 non-null   float64
 48  series_completion_rate        8579 non-null   float64
 49  content_genre_preference      8579 non-null   object
 50  peak_viewing_hour             8579 non-null   object
 51  primary_device                8579 non-null   object
 52  num_devices_registered        8579 non-null   int64
 53  download_feature_used         8579 non-null   object
 54  live_to_vod_ratio             8579 non-null   float64
 55  subscription_plan             8579 non-null   object
 56  payment_failures              8579 non-null   float64
 57  plan_change_history           8579 non-null   object
 58  age_group                     8579 non-null   object
 59  tenure_group                  8579 non-null   object
 60  support_priority              8579 non-null   object
 61  satisfaction_group            8579 non-null   object
 62  discount_group                8579 non-null   object
 63  activity_status               8579 non-null   object
 64  spend_tier                    8579 non-null   object
 65  churn_status                  8579 non-null   object
 66  sports_engagement             8579 non-null   object
 67  betting_intensity             8579 non-null   object
 68  customer_value_segment        8579 non-null   object
 69  risk_profile                  8579 non-null   object
 70  win_rate_segment              8579 non-null   object
 71  stake_tier                    8579 non-null   object
 72  gain_segment                  8579 non-null   object
 73  ggr_segment                   8579 non-null   object
 74  playtime_segment              8579 non-null   object
 75  purchase_behavior             8579 non-null   object
 76  session_intensity             8579 non-null   object
 77  session_duration_tier         8579 non-null   object
 78  ad_spend_tier                 8579 non-null   object
 79  ctr_tier                      8579 non-null   object
 80  conversion_tier               8579 non-null   object
 81  site_engagement_tier          8579 non-null   object
 82  loyalty_tier                  8579 non-null   object
 83  roas_segment                  8579 non-null   object
 84  session_duration_segment      8579 non-null   object
 85  viewer_segment                8579 non-null   object
 86  completion_segment            8579 non-null   object
 87  device_segment                8579 non-null   object
 88  content_preference_segment    8579 non-null   object
 89  payment_risk_segment          8579 non-null   object
dtypes: float64(24), int64(8), object(58)
memory usage: 6.0+ MB

In [ ]:
df.dtypes

subscriber_id                  object
age                             int64
gender                         object
subscription_tenure_months    float64
region                         object
                               ...
viewer_segment                 object
completion_segment             object
device_segment                 object
content_preference_segment     object
payment_risk_segment           object
Length: 90, dtype: object

In [ ]:
df.describe()

,age,subscription_tenure_months,support_tickets_raised,satisfaction_score,promo_discount_pct,days_since_last_activity,monthly_spend_eur,churn,sports_events_watched_month,bets_placed_total,...,conversion_rate,time_on_site_mins,loyalty_points,roas,avg_session_duration_mins,titles_watched_per_month,series_completion_rate,num_devices_registered,live_to_vod_ratio,payment_failures
count,8579.000000,8579.000000,8579.000000,8579.000000,8579.000000,8579.000000,8579.000000,8579.000000,8579.000000,8579.000000,...,8579.000000,8579.000000,8579.000000,8579.000000,8579.000000,8579.000000,8579.000000,8579.000000,8579.000000,8579.000000
mean,43.802308,29.575094,2.032055,5.576408,12.495463,204.587413,46.088224,0.148269,4.634107,20.008626,...,0.103643,7.732278,2508.268097,220.692273,127.038372,37.419195,0.498185,3.535843,0.500470,0.307522
std,13.970152,17.094438,1.422441,2.706664,4.329692,171.235668,10.345405,0.355387,6.258279,4.445485,...,0.055046,4.209894,1428.978237,129.031961,107.385964,20.025180,0.288453,1.721374,0.290084,0.690503
min,16.000000,0.000000,0.000000,0.000000,4.620000,0.000000,0.000000,0.000000,0.000000,6.000000,...,0.000000,0.290000,0.000000,0.000000,0.250000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,33.000000,15.000000,1.000000,3.000000,8.755000,92.000000,39.720000,0.000000,0.000000,17.000000,...,0.055750,4.085000,1287.000000,107.480000,63.890000,20.000000,0.250000,2.000000,0.250000,0.000000
50%,44.000000,29.000000,2.000000,6.000000,12.540000,186.000000,46.330000,0.000000,0.000000,20.000000,...,0.102600,7.730000,2515.000000,221.550000,123.000000,40.000000,0.490000,4.000000,0.500000,0.000000
75%,55.000000,44.015000,3.000000,8.000000,16.220000,278.985000,52.960000,0.000000,9.000000,23.000000,...,0.150000,11.400000,3713.500000,332.825000,179.200000,60.000000,0.750000,5.000000,0.750000,0.030000
max,71.000000,61.210000,9.000000,10.000000,20.360000,999.000000,137.620000,1.000000,20.000000,39.000000,...,0.200000,15.390000,5109.000000,457.680000,1440.000000,60.000000,1.000000,6.000000,1.000000,3.000000

In [ ]:
# Number of missing values ​​in each column
missing_data = df.isnull().sum()
print(missing_data) # Display only the columns that are missing

subscriber_id                 0
age                           0
gender                        0
subscription_tenure_months    0
region                        0
                             ..
viewer_segment                0
completion_segment            0
device_segment                0
content_preference_segment    0
payment_risk_segment          0
Length: 90, dtype: int64

In [ ]:
# Selecting float and int columns only
num_cols = df.select_dtypes(include=['float64', 'int64']).columns

# Checking for negative values in the specified columns
for col in num_cols:
    if col in df.columns:
        neg_count = len(df[df[col] < 0])
        if neg_count > 0:
            print(f"⚠️ col '{col}': there are {neg_count} negative values")
        else:
            print(f"✅ col '{col}': clean (no negative values)")

✅ col 'age': clean (no negative values)
✅ col 'subscription_tenure_months': clean (no negative values)
✅ col 'support_tickets_raised': clean (no negative values)
✅ col 'satisfaction_score': clean (no negative values)
✅ col 'promo_discount_pct': clean (no negative values)
✅ col 'days_since_last_activity': clean (no negative values)
✅ col 'monthly_spend_eur': clean (no negative values)
✅ col 'churn': clean (no negative values)
✅ col 'sports_events_watched_month': clean (no negative values)
✅ col 'bets_placed_total': clean (no negative values)
✅ col 'avg_bet_amount_eur': clean (no negative values)
✅ col 'avg_betting_odds': clean (no negative values)
✅ col 'betting_win_rate': clean (no negative values)
✅ col 'total_stake_eur': clean (no negative values)
✅ col 'total_gain_eur': clean (no negative values)
⚠️ col 'total_ggr': there are 1980 negative values
✅ col 'gaming_playtime_hours_weekly': clean (no negative values)
✅ col 'in_app_purchases_gaming': clean (no negative values)
✅ col 'gaming_sessions_per_week': clean (no negative values)
✅ col 'avg_gaming_session_mins': clean (no negative values)
⚠️ col 'ad_spend_eur': there are 62 negative values
✅ col 'ctr': clean (no negative values)
✅ col 'conversion_rate': clean (no negative values)
✅ col 'time_on_site_mins': clean (no negative values)
✅ col 'loyalty_points': clean (no negative values)
✅ col 'roas': clean (no negative values)
✅ col 'avg_session_duration_mins': clean (no negative values)
✅ col 'titles_watched_per_month': clean (no negative values)
✅ col 'series_completion_rate': clean (no negative values)
✅ col 'num_devices_registered': clean (no negative values)
✅ col 'live_to_vod_ratio': clean (no negative values)
✅ col 'payment_failures': clean (no negative values)

In [ ]:
# Selecting text columns only
text_cols = df.select_dtypes(include=['object']).columns

# Checking hidden spaces (extra spaces)
for col in text_cols:
    has_spaces = df[col].astype(str).str.contains(r'^\s|\s$', regex=True).sum() # counts how many values in column [col] have spaces at the beginning or end

    if has_spaces > 0:
        print(f"⚠️ col [{col}]: there are {has_spaces} rows with extra spaces")
    else:
        print(f"✅ col [{col}]: clean (no extra spaces)")

✅ col [subscriber_id]: clean (no extra spaces)
✅ col [gender]: clean (no extra spaces)
✅ col [region]: clean (no extra spaces)
✅ col [payment_method]: clean (no extra spaces)
✅ col [live_sports_subscriber]: clean (no extra spaces)
✅ col [favourite_live_sport]: clean (no extra spaces)
✅ col [live_event_spike_signup]: clean (no extra spaces)
✅ col [stream_quality_preference]: clean (no extra spaces)
✅ col [favourite_sport]: clean (no extra spaces)
✅ col [preferred_bet_type]: clean (no extra spaces)
✅ col [betting_enabled]: clean (no extra spaces)
✅ col [responsible_gambling_flag]: clean (no extra spaces)
✅ col [betting_profile]: clean (no extra spaces)
✅ col [game_genre_preference]: clean (no extra spaces)
✅ col [gaming_engagement_level]: clean (no extra spaces)
✅ col [ott_gaming_app_used]: clean (no extra spaces)
✅ col [acquisition_channel]: clean (no extra spaces)
✅ col [acquisition_campaign_type]: clean (no extra spaces)
✅ col [used_free_trial]: clean (no extra spaces)
✅ col [promo_discount_applied]: clean (no extra spaces)
✅ col [content_genre_preference]: clean (no extra spaces)
✅ col [peak_viewing_hour]: clean (no extra spaces)
✅ col [primary_device]: clean (no extra spaces)
✅ col [download_feature_used]: clean (no extra spaces)
✅ col [subscription_plan]: clean (no extra spaces)
✅ col [plan_change_history]: clean (no extra spaces)
✅ col [age_group]: clean (no extra spaces)
✅ col [tenure_group]: clean (no extra spaces)
✅ col [support_priority]: clean (no extra spaces)
✅ col [satisfaction_group]: clean (no extra spaces)
✅ col [discount_group]: clean (no extra spaces)
✅ col [activity_status]: clean (no extra spaces)
✅ col [spend_tier]: clean (no extra spaces)
✅ col [churn_status]: clean (no extra spaces)
✅ col [sports_engagement]: clean (no extra spaces)
✅ col [betting_intensity]: clean (no extra spaces)
✅ col [customer_value_segment]: clean (no extra spaces)
✅ col [risk_profile]: clean (no extra spaces)
✅ col [win_rate_segment]: clean (no extra spaces)
✅ col [stake_tier]: clean (no extra spaces)
✅ col [gain_segment]: clean (no extra spaces)
✅ col [ggr_segment]: clean (no extra spaces)
✅ col [playtime_segment]: clean (no extra spaces)
✅ col [purchase_behavior]: clean (no extra spaces)
✅ col [session_intensity]: clean (no extra spaces)
✅ col [session_duration_tier]: clean (no extra spaces)
✅ col [ad_spend_tier]: clean (no extra spaces)
✅ col [ctr_tier]: clean (no extra spaces)
✅ col [conversion_tier]: clean (no extra spaces)
✅ col [site_engagement_tier]: clean (no extra spaces)
✅ col [loyalty_tier]: clean (no extra spaces)
✅ col [roas_segment]: clean (no extra spaces)
✅ col [session_duration_segment]: clean (no extra spaces)
✅ col [viewer_segment]: clean (no extra spaces)
✅ col [completion_segment]: clean (no extra spaces)
✅ col [device_segment]: clean (no extra spaces)
✅ col [content_preference_segment]: clean (no extra spaces)
✅ col [payment_risk_segment]: clean (no extra spaces)

In [ ]:
df.to_csv('Cleaned OTT Subscriber with Grouping.csv', index=False)